# LangChain RAG pipeline (modular)

Hadith RAG over `data/dorar_hadith_full_batch_2.csv`. Each section below is one pipeline stage; change **`CONFIG`** in the next cell to swap models, chunking, or retrieval without touching the rest.

**Run order:** Config → Imports → Load → Split → Embeddings → Vector store → Retriever → LLM → Prompt → Chain → Query.

**Requirements:** `pip install -r requirements.txt` (optional: copy `.env.example` to `.env` for API keys).

**Changes from base:**
- `load_hadith_documents` deduplicates hadiths per sharh group on `(hadith, rawy)` so duplicate CSV rows do not inflate metadata lists.
- `retrieve_filtered` uses **exact match** for controlled-vocab columns (`rawy`, `hokm`, `mohadth`, `source`) and **substring/contains match** for free-text columns (`categories`, …). `k_fetch` raised to `k_target × 10` so rare filters still return enough results.
- `EXACT_MATCH_COLUMNS` set makes the match-mode configurable without touching the filter loop.
- BLEU & ROUGE evaluation uses **`best_match` strategy**: ground-truth `Hadith_Matn` is compared against every retrieved hadith individually and the best score is reported — correct when retrieval returns multiple hadiths per chunk.
- **Tashkeel is stripped from both sides** before BLEU/ROUGE comparison via `normalize_arabic` (also normalizes أإآ→ا, ة→ه, ى→ي). Retrieved hadiths are pre-normalized at collection time so diacritical differences between the scraped index and the eval CSV do not inflate miss-rates.
- `strategy` config key in `EVAL_CONFIG["bleu_rouge"]` is now respected: `"best_match"` computes only best-match scores, `"concatenate"` computes only concat scores, anything else computes both.

In [1]:
# import re
# import pandas as pd
# TASHKEEL = re.compile(r'[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]')
#
# def normalize(text):
#     if pd.isna(text):
#         return text
#     text = re.sub(TASHKEEL, '', text)
#     return text
#
# df = pd.read_csv("data/dorar_hadith_full_batch_2.csv")
# df['sharh'] = df['sharh'].apply(normalize)
# df.to_csv("data/dorar_hadith_without_tashkeel.csv")

# Data

In [2]:
!python -m pip install -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt

Requirement already satisfied: langchain>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 1)) (1.2.15)
Requirement already satisfied: langchain-core>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (1.2.28)
Collecting langchain-community>=0.3.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3))
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain-openai>=0.2.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 4))
  Downloading langchain_openai-1.3.3-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain-text-splitters>=0.3.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 5))
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting langchain-chroma>=0.1.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 6))
  Downloading langchain_chroma-1.1.0-py3-none-any.whl.metadata (1.9 kB)
Collecting chromadb>=0.5.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 8)) (2.3.3)
Requirement already satisfied: python-dotenv>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 9)) (1.2.2)
Requirement already satisfied: sentence-transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (5.4.0)
Collecting langchain_groq>=1.1.2 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 11))
  Downloading langchain_groq-1.1.3-py3-none-any.whl.metadata (2.9 kB)
Collecting ragas>=0.2.14 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12))
  Downloading ragas-0.4.3-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: datasets>=2.14.0 in /usr/local/lib/python3.12/dist-packages (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (4.8.5)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 1)) (1.1.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 1)) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (0.7.30)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (26.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (0.14.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (0.4.3)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3))
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting langchain-core>=0.3.0 (from -r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2))
  Downloading langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (2.4.6)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (2.13.1)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3))
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (2.0.49)
Collecting langchain-protocol>=0.0.17 (from langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2))
  Downloading langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai>=0.2.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai>=0.2.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 4)) (0.12.0)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.5.0)
Collecting pybase64>=1.4.1 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.44.0)
Collecting onnxruntime>=1.14.1 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.80.0)
Collecting bcrypt>=4.0.1 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7))
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (4.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 8)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 8)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 8)) (2026.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (1.10.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (2.10.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (1.16.3)
Collecting groq<1.0.0,>=0.30.0 (from langchain_groq>=1.1.2->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 11))
  Downloading groq-0.37.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12)) (1.6.0)
Collecting appdirs (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12))
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting diskcache>=5.6.3 (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12))
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting instructor (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12))
  Downloading instructor-1.15.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12)) (11.3.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12)) (3.6.1)
Collecting scikit-network (from ragas>=0.2.14->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 12))
  Downloading scikit_network-0.33.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (0.4.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=2.14.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 13)) (2025.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 3)) (1.23.0)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain_groq>=1.1.2->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 11)) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain_groq>=1.1.2->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 11)) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain_groq>=1.1.2->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 11)) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=3.0.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 10)) (1.4.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core>=0.3.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 2)) (3.1.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb>=0.5.0->-r /kaggle/input/datasets/aliabdelmenam/gg-data/requirements.txt (line 7)) (0.37.0)

In [3]:
import gdown

url = 'https://drive.google.com/uc?id=1QTOg3OeNSsJ0jh6llOw4BjeedyQZ2v-p'
gdown.download(url, quiet=False, use_cookies=False)

Downloading...
From (original): https://drive.google.com/uc?id=1QTOg3OeNSsJ0jh6llOw4BjeedyQZ2v-p
From (redirected): https://drive.google.com/uc?id=1QTOg3OeNSsJ0jh6llOw4BjeedyQZ2v-p&confirm=t&uuid=4f0a7445-60c1-4085-bb86-b949de7cdd3f
To: /kaggle/working/my_scraped_data.csv
100%|██████████| 847M/847M [00:05<00:00, 153MB/s]

'my_scraped_data.csv'

In [4]:
import pandas as pd

gg = pd.read_csv("/kaggle/working/my_scraped_data.csv")
gg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226389 entries, 0 to 226388
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   page_id     226389 non-null  int64
 1   url         226389 non-null  object
 2   categories  226373 non-null  object
 3   sharh       222599 non-null  object
 4   hadith      226389 non-null  object
 5   rawy        218543 non-null  object
 6   mohadth     226389 non-null  object
 7   source      226389 non-null  object
 8   page        226389 non-null  object
 9   hokm        226389 non-null  object
 10  takhrij     213849 non-null  object
dtypes: int64(1), object(10)
memory usage: 19.0+ MB

In [5]:
df = gg.copy(deep=True)

In [6]:
# Only remove brackets if the string starts with '[' AND ends with ']'
mask = df['hokm'].str.startswith('[', na=False) & df['hokm'].str.endswith(']', na=False)
df.loc[mask, 'hokm'] = df.loc[mask, 'hokm'].str[1:-1]

mask = df['rawy'].str.startswith('[', na=False) & df['rawy'].str.endswith(']', na=False)
df.loc[mask, 'rawy'] = df.loc[mask, 'rawy'].str[1:-1]

mask = df['mohadth'].str.startswith('[', na=False) & df['mohadth'].str.endswith(']', na=False)
df.loc[mask, 'mohadth'] = df.loc[mask, 'mohadth'].str[1:-1]

display(df['hokm'].value_counts().head(60))

hokm
صحيح                                                                       112359
إسناده صحيح                                                                 18841
حسن                                                                          9394
أخرجه في صحيحه                                                               7238
إسناده حسن                                                                   6049
إسناده صحيح على شرط الشيخين                                                  4491
حسن صحيح                                                                     3832
إسناده صحيح على شرط مسلم                                                     3442
صحيح لغيره                                                                   2732
ثابت                                                                         2572
إسناده جيد                                                                   2053
سكت عنه [وقد قال في رسالته لأهل مكة كل ما سكت عنه فهو صالح]                  1441
رجاله ثقات                                                                   1285
حسن كما قال في المقدمة                                                       1188
حسن لغيره                                                                    1041
إسناده صحيح أو حسن أو ما قاربهما                                             1006
رجاله رجال الصحيح                                                             976
إسناده قوي                                                                    963
احتج به ، وقال في المقدمة: (لم نحتج إلا بخبر صحيح من رواية الثقات مسند)       747
أشار في المقدمة أنه صحيح الإسناد                                              740
إسناده صحيح على شرط البخاري                                                   736
ضعيف                                                                          700
طريقه صحيح                                                                    651
حسن غريب                                                                      580
إسناده صحيح على شرطهما                                                        578
صحيح أو حسن [كما اشترط على نفسه في المقدمة]                                   505
معلق                                                                          441
صحيح على شرط الشيخين                                                          409
أشار في المقدمة إلى صحته                                                      397
سنده صحيح                                                                     392
إسناده ضعيف                                                                   383
صحيح على شرط مسلم                                                             381
صحيح [لغيره]                                                                  378
أشار في المقدمة أنه صح وثبت بالإسناد الثابت الصحيح                            361
[اشترط في المقدمة أنه] صحيح على طريقة بعض أهل الحديث                          323
صحيح الإسناد                                                                  312
صحيح موقوف                                                                    239
رواته ثقات                                                                    227
مرسل                                                                          217
له شاهد                                                                       197
إسناده صحيح رجاله ثقات                                                        192
غريب                                                                          180
صحيح بمجموع طرقه                                                              180
سنده حسن                                                                      172
إسناده لا بأس به                                                              171
إسناده على شرط مسلم                                                           169
له متابعة                                                                     164
صحيح بشواهده                                                                  161
رجاله رجال الصحيح‏‏                                                           158
جيد                                                                           157
إسناده رجاله ثقات                                                             154
صحيح ثابت                                                                     151
متواتر                                                                        150
رجاله موثقون                                                                  149
حسن غريب من هذا الوجه                                                         142
منكر                                                                          135
محفوظ                                                                         134
أورده في المختارة وقال [هذه أحاديث اخترتها مما ليس في البخاري ومسلم]          129
إسناده صالح                                                                   124
لا يصح                                                                        117
Name: count, dtype: int64

In [7]:
df.drop(['page_id','url','sharh'],axis=1).duplicated().sum()

np.int64(241)

# Config

In [8]:
from pathlib import Path

CONFIG = {
  "paths": {
    "data_csv": Path("/kaggle/working/my_scraped_data.csv"),
    "chroma_dir": Path("chroma_db"),
    "collection_name": "hadith_rag",
  },
  "data": {
    "max_rows": None,
    "text_columns": ["sharh"],
    "metadata_columns":
        ["page_id", "url", "categories", "hadith",
         "rawy", "mohadth",
         "source", "hokm", "page", "takhrij"],
  },
  "chunking": {
    "chunk_size": 350,
    "chunk_overlap": 35,
    # "separators": ["."],
  },
  "embeddings": {
    "provider": "huggingface",
    "model_name": "Omartificial-Intelligence-Space/Arabic-Triplet-Matryoshka-V2",
    "openai_model": "text-embedding-3-small",
  },
  "vector_store": {
    "persist": True,
    "reset_on_build": True,
  },
  "retriever": {
    "search_type": "similarity",
    "k": 8,
    "fetch_k": 25,
    "lambda_mult": 0.5,
  },
  "llm": {
    "provider": "huggingface_local",
    "openai_model": "gpt-4o-mini",
    "ollama_model": "llama3.2",
    "groq_model": "llama-3.3-70b-versatile",
    "huggingface_model": "silma-ai/SILMA-Kashif-2B-Instruct-v1.0", # Fixed Typo here!
    "temperature": 0.1,
  },
  "prompt": {
    "language": "ar",
    "system_role": (
      "أنت عالم دين إسلامي متخصص، مهمتك الإجابة عن أسئلة المستخدمين بناءً فقط على النص المُسند إليك. "
      "امتنع تمامًا عن تأليف أي أقوال دينية أو اجتهادات شخصية غير واردة في النص المقدّم. "
      "عند الاستشهاد بالأحاديث، الزم بتخريجها مع ذكر المصدر (الكتاب، رقم الحديث)، ودرجة صحتها (صحيح، حسن، ضعيف، موضوع) بحسب ما ورد في المصادر المعتمدة. "
      "إذا لم تجد إجابة وافية في السياق المتاح، أو كان السؤال خارج نطاق النص، فلا تفتِ من عندك، بل وجّه المستخدم إلى ضرورة استشارة عالم أو مؤسسة دينية موثوقة للحصول على فتوى دقيقة ومناسبة. "
      "التزم بالأدب الجم، والوضوح، والاختصار، مع الحرص على تعزيز الطمأنينة النفسية للمستخدم."
    ),
  },
}

PROJECT_ROOT = Path(".").resolve()

# Safe absolute path assignment
if not CONFIG["paths"]["data_csv"].is_absolute():
    CONFIG["paths"]["data_csv"] = PROJECT_ROOT / CONFIG["paths"]["data_csv"]

if not CONFIG["paths"]["chroma_dir"].is_absolute():
    CONFIG["paths"]["chroma_dir"] = PROJECT_ROOT / CONFIG["paths"]["chroma_dir"]

In [9]:
import os
import shutil
from typing import Any

import pandas as pd
from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_text_splitters import RecursiveCharacterTextSplitter
import re
load_dotenv()

def cfg(*keys: str) -> Any:
    """Read nested CONFIG values, e.g. cfg('retriever', 'k')."""
    node = CONFIG
    for key in keys:
        node = node[key]
    return node

In [10]:
ARABIC_TASHKEEL = re.compile(r"[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]")
NON_WORD = re.compile(r"[^\w\s\u0600-\u06FF]+", re.UNICODE)

In [11]:

def normalize_arabic(text: str) -> str:
    if text is None or (isinstance(text, float) and pd.isna(text)):
        return ""
    text = str(text)
    text = ARABIC_TASHKEEL.sub("", text)
    text = text.replace("\ufeff", "")
    text = re.sub(r"[إأآٱ]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)
    text = NON_WORD.sub(" ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [ ]:
import ast
from typing import Union
import pandas as pd
from pathlib import Path
from langchain_core.documents import Document

# ── Constants ────────────────────────────────────────────────
HADITH_LEVEL_LIST_COLUMNS = ["hadith", "rawy", "mohadth", "source", "hokm", "takhrij",
                              "page_id", "url", "categories", "page"]
EMBED_COLUMN = "sharh"
SCALAR_META_COLUMNS = []

# ── Helpers ─────────────────────────────────────────────────
def _parse_to_list(val) -> list[str]:
    if isinstance(val, list): return [str(x) for x in val]
    if not isinstance(val, str): return [str(val)] if pd.notna(val) else [""]
    s = val.strip()
    if s.startswith("["):
        try:
            res = ast.literal_eval(s)
            return [str(x) for x in res] if isinstance(res, list) else [str(res)]
        except: pass
    return [s]

def load_hadith_documents(csv_path=None, max_rows: int | None = None) -> list[Document]:
    csv_path = Path(csv_path or cfg("paths", "data_csv"))

    df = pd.read_csv(csv_path)

    if max_rows:
        df = df.head(max_rows)

    df = df[df[EMBED_COLUMN].notna()]

    docs = []

    for sharh_text, group in df.groupby(EMBED_COLUMN, sort=False):

        group_records = []

        for _, row in group.iterrows():

            row_data = {
                col: _parse_to_list(row.get(col, ""))
                for col in HADITH_LEVEL_LIST_COLUMNS
            }

            n = len(row_data["hadith"])

            for i in range(n):
                record = {
                    col: (
                        row_data[col][i]
                        if i < len(row_data[col])
                        else ""
                    )
                    for col in HADITH_LEVEL_LIST_COLUMNS
                }

                group_records.append(record)

        metadata = {}

        for col in HADITH_LEVEL_LIST_COLUMNS:
            metadata[col] = [rec[col] for rec in group_records]

        docs.append(
            Document(
                page_content=str(sharh_text).strip(),
                metadata=metadata,
            )
        )

    print(f"Loaded {len(docs)} documents with proper metadata alignment.")
    return docs


from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

# In-memory parent store — full parent docs indexed by parent_id
PARENT_STORE: list[Document] = []
from transformers import AutoTokenizer
from langchain_core.documents import Document

PARENT_STORE: list[Document] = []

def build_child_chunks(
    raw_docs: list[Document],
    chunk_size: int = 350,
    chunk_overlap: int = 32,
    model_name: str = "Omartificial-Intelligence-Space/Arabic-Triplet-Matryoshka-V2",
) -> list[Document]:
    global PARENT_STORE
    PARENT_STORE = []

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    def split_by_tokens(text: str) -> list[str]:
        tokens = tokenizer.encode(text, add_special_tokens=False)
        chunks = []
        step = chunk_size - chunk_overlap
        for i in range(0, len(tokens), step):
            chunk_tokens = tokens[i : i + chunk_size]
            chunk_text = tokenizer.decode(chunk_tokens, skip_special_tokens=True)
            if chunk_text.strip():
                chunks.append(chunk_text.strip())
        return chunks

    child_docs: list[Document] = []

    for parent_id, parent_doc in enumerate(raw_docs):
        PARENT_STORE.append(parent_doc)

        chunks = split_by_tokens(parent_doc.page_content)

        for chunk_idx, chunk_text in enumerate(chunks):
            child_meta = {
                "parent_id":   parent_id,
                "chunk_index": chunk_idx,
                "rawy":        parent_doc.metadata.get("rawy", []),
                "hokm":        parent_doc.metadata.get("hokm", []),
                "mohadth":     parent_doc.metadata.get("mohadth", []),
                "source":      parent_doc.metadata.get("source", []),
                "categories":  parent_doc.metadata.get("categories", []),
            }
            child_docs.append(Document(page_content=chunk_text, metadata=child_meta))

    print(f"Parents: {len(PARENT_STORE)} | Child chunks: {len(child_docs)}")
    return child_docs

In [13]:
# print(len(raw_documents[0].metadata['hadith']))
# print(len(raw_documents[0].metadata['url']))

In [14]:
# ── Pre-index filter ─────────────────────────────────────────────────────────
ACTIVE_FILTERS: dict = {
    # "rawy": ["البخاري", "مسلم"],
    # "hokm": "صحيح",
}

# Fix: Load the documents first so 'raw_documents' is defined
raw_documents = load_hadith_documents(
    cfg("paths", "data_csv"),
    max_rows=cfg("data", "max_rows")
)

# Note: This code expects 'filter_documents' to be defined.
# If it was removed, we use the documents directly or define a simple filter helper.
def filter_documents(docs, **filters):
    if not filters: return docs
    norm = {k: ([v.lower()] if isinstance(v, str) else [x.lower() for x in v]) for k, v in filters.items()}
    return [d for d in docs if all(any(f in str(d.metadata.get(k, '')).lower() for f in allowed) for k, allowed in norm.items())]

# documents_to_index = (
#     filter_documents(raw_documents, **ACTIVE_FILTERS)
#     if ACTIVE_FILTERS
#     else raw_documents
# )
filtered_parents = (
    filter_documents(raw_documents, **ACTIVE_FILTERS)
    if ACTIVE_FILTERS
    else raw_documents
)
documents_to_index = build_child_chunks(
    filtered_parents,
    chunk_size=cfg("chunking", "chunk_size"),
    chunk_overlap=cfg("chunking", "chunk_overlap"),
)

# print(f"\nDocuments to index: {len(documents_to_index)}")
# print(documents_to_index[0].page_content[:300] if documents_to_index else "— empty —")
print(f"Child chunks to index: {len(documents_to_index)}")
# print(documents_to_index[0].page_content[:200] if documents_to_index else "— empty —")

Loaded 14691 documents with proper metadata alignment.

config.json:   0%|          | 0.00/637 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1183 > 512). Running this sequence through the model will result in indexing errors

Parents: 14691 | Child chunks: 22643
Child chunks to index: 22643

In [15]:
len(documents_to_index)

22643

In [16]:
len(raw_documents)

14691

In [17]:
raw_documents[0].page_content

'أرسل الله تعالى نبيه محمدا صلى الله عليه وسلم رحمة للعالمين، وجعل في امتثال أمره واجتناب نهيه النجاة في الدنيا والآخرة، فكانت طريقته التيسير على الناس في عباداتهم وحياتهم. وفي هذا الحديث يروي أبو هريرة رضي الله عنه أن رسول الله صلى الله عليه وسلم رأى رجلا ماشيا على قدميه، ويسوق أمامه بدنة قد أهداها إلى البيت الحرام يتقرب بها إلى الله تعالى، والبدنة: تكون من الإبل خاصة، وقيل: البدن تطلق على الإبل والبقر. فأمره النبي صلى الله عليه وسلم بركوبها؛ ليستريح من تعبه الذي حصل له من مشقة المشي، فأخبره الرجل أنها بدنة مهداة إلى الكعبة، فكيف يركبها؟ فقال له النبي صلى الله عليه وسلم في المرة الثانية أو الثالثة: «اركبها، ويلك!» وأصل الويل: العذاب الشديد، وهو غير مقصود هنا، وإنما أراد النبي صلى الله عليه وسلم أن يغلظ له في القول ليركبها. وفي الحديث: مشروعية ركوب الهدي. وفيه: الندب إلى المبادرة إلى امتثال أمر الله ورسوله، وزجر من لم يبادر إلى ذلك، وتوبيخه.'

In [18]:
len(raw_documents[0].metadata['hadith'])

31

In [19]:
print(len(documents_to_index[0].metadata['rawy']))
print(len(documents_to_index[0].metadata['source']))
print(len(documents_to_index[0].metadata['hokm']))

31
31
31

In [20]:
documents_to_index[0].metadata.keys()

dict_keys(['parent_id', 'chunk_index', 'rawy', 'hokm', 'mohadth', 'source', 'categories'])

In [21]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.device_count())

2.10.0+cu128
12.8
True
2

In [22]:
!pip install langchain_huggingface

Collecting langchain_huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.10.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (1.4.8)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain_huggingface) (0.22.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.7.30)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.34.2)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain_huggingface) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain_huggingface) (0.1.2)
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Installing collected packages: langchain_huggingface
Successfully installed langchain_huggingface-1.2.2

In [23]:
def build_embeddings():
    provider = cfg("embeddings", "provider")
    if provider == "openai":
        from langchain_openai import OpenAIEmbeddings
        return OpenAIEmbeddings(model=cfg("embeddings", "openai_model"))
    if provider == "huggingface":
        from langchain_huggingface import HuggingFaceEmbeddings
        import torch

        device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Using device: {device}")

        return HuggingFaceEmbeddings(
            model_name=cfg("embeddings", "model_name"),
            model_kwargs={"device": device},
            encode_kwargs={"batch_size": 256},
        )
    raise ValueError(f"Unknown embeddings provider: {provider}")


embeddings = build_embeddings()
print(f"Embeddings ready: {cfg('embeddings', 'provider')} / {cfg('embeddings', 'model_name') if cfg('embeddings', 'provider') == 'huggingface' else cfg('embeddings', 'openai_model')}")

Using device: cuda

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/541M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

Embeddings ready: huggingface / Omartificial-Intelligence-Space/Arabic-Triplet-Matryoshka-V2

In [24]:
!pip install langchain_chroma

Requirement already satisfied: langchain_chroma in /usr/local/lib/python3.12/dist-packages (1.1.0)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.5.9)
Requirement already satisfied: langchain-core<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (1.4.8)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain_chroma) (2.4.6)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.13.1)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.44.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.27.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.43.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.43.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.43.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.24.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (36.0.2)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.26.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.7.30)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.14.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.1.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.34.2)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.10)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.13.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.1.3->langchain_chroma) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain_chroma) (5.29.5)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.74.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.43.0)
Requirement already satisfied: opentelemetry-proto==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.43.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.64b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.10.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain_chroma) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.23.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain_chroma) (1.4.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain_chroma) (3.3.1)

In [25]:
from langchain_chroma import Chroma
import shutil

chroma_dir = cfg("paths", "chroma_dir")
collection = cfg("paths", "collection_name")

if cfg("vector_store", "reset_on_build") and chroma_dir.exists():
    shutil.rmtree(chroma_dir)
    print(f"Removed {chroma_dir}")

# Updated to use Cosine Similarity
vectorstore = Chroma(
    collection_name=collection,
    embedding_function=embeddings,
    persist_directory=str(chroma_dir) if cfg("vector_store", "persist") else None,
    collection_metadata={"hnsw:space": "cosine"}
)

def _collection_has_vectors(vs: Chroma) -> bool:
    data = vs.get(limit=1)
    return bool(data.get("ids"))

if not _collection_has_vectors(vectorstore):
    from tqdm import tqdm

    if 'documents_to_index' not in globals():
        print("Variable 'documents_to_index' not found. Defaulting to 'raw_documents'.")
        documents_to_index = raw_documents

    batch_size = 512
    for i in tqdm(range(0, len(documents_to_index), batch_size)):
        vectorstore.add_documents(documents_to_index[i : i + batch_size])

    print(f"Indexed {len(documents_to_index)} documents into '{collection}' with Cosine Similarity")
else:
    n = len(vectorstore.get().get("ids", []))
    print(f"Using existing index: {n} vectors in '{collection}'")

vectorstore

100%|██████████| 45/45 [08:32<00:00, 11.40s/it]

Indexed 22643 documents into 'hadith_rag' with Cosine Similarity

## Retriever — per-hadith aligned metadata filtering

**Fix #1:** `retrieve_filtered` now trims metadata down to only the rows that match
the active filter.  If `rawy=["البخاري"]` and a chunk has 10 hadiths of which 3
belong to البخاري, only those 3 hadiths are returned — along with their paired
`mohadth`, `source`, `hokm`, and `takhrij` at the same list index.

In [26]:
from dataclasses import dataclass, field
import ast
import pandas as pd


@dataclass
class RetrievedResult:
    """
    One entry returned by retrieve_filtered().
    """
    sharh: str
    hadiths: list[str]
    list_meta: dict = field(default_factory=dict)
    scalar_meta: dict = field(default_factory=dict)
    score: float | None = None

    def __repr__(self):
        preview = self.sharh[:80].replace("\n", " ")
        return (
            f"RetrievedResult(\n"
            f"  hadiths_count={len(self.hadiths)},\n"
            f"  rawy={self.list_meta.get('rawy', 'N/A')!r},\n"
            f"  hokm={self.list_meta.get('hokm', 'N/A')!r},\n"
            f"  categories={self.list_meta.get('categories', 'N/A')!r},\n"
            f"  url={self.list_meta.get('url', 'N/A')!r},\n"
            f"  page={self.list_meta.get('page', 'N/A')!r},\n"
            f"  sharh_preview={preview!r}...\n"
            f")"
        )

# All hadith-level columns stored as parallel lists in each Document's metadata
HADITH_LEVEL_LIST_COLUMNS = ["hadith", "rawy", "mohadth", "source", "hokm", "takhrij",
                              "page_id", "url", "categories", "page"]

SHARH_LEVEL_SCALAR_COLUMNS = []

# Columns where filtering should be an EXACT match (controlled vocabulary).
# Everything else uses substring / contains matching (free-text fields).
EXACT_MATCH_COLUMNS = {"rawy", "hokm", "mohadth", "source"}

def _safe_parse_list(raw) -> list[str]:
    """Safely coerce a Chroma metadata value back to a Python list of strings.
    Chroma stores lists as their repr strings, so we always need ast.literal_eval."""
    if isinstance(raw, list):
        return [str(v) if (v and pd.notna(v)) else "" for v in raw]
    if isinstance(raw, str) and raw.startswith("["):
        try:
            parsed = ast.literal_eval(raw)
            return [str(v) if (v and pd.notna(v)) else "" for v in parsed]
        except Exception:
            pass
    if raw is None or (isinstance(raw, float) and pd.isna(raw)):
        return [""]
    return [str(raw)]

def _build_row_records(meta: dict) -> list[dict]:
    parsed: dict[str, list[str]] = {
        col: _safe_parse_list(meta.get(col, []))
        for col in HADITH_LEVEL_LIST_COLUMNS
    }
    n_rows = len(parsed.get("hadith", []))
    if n_rows == 0: return []

    records = []
    for i in range(n_rows):
        row = {}
        for col in HADITH_LEVEL_LIST_COLUMNS:
            vals = parsed[col]
            row[col] = vals[i] if i < len(vals) else ""
        records.append(row)
    return records

def _filter_row_records(records: list[dict], norm_filters: dict[str, list[str]]) -> list[dict]:
    """
    AND across columns, OR within a column's allowed list.
    - Controlled-vocab columns (rawy, hokm, …): exact equality match.
    - Free-text columns (categories, …): substring / contains match.
    """
    if not norm_filters: return records
    kept = []
    for rec in records:
        passes = True
        for col, allowed in norm_filters.items():
            val = str(rec.get(col, "")).lower()
            if col in EXACT_MATCH_COLUMNS:
                # Exact match: the cell value must equal one of the allowed values
                if not any(a == val for a in allowed):
                    passes = False
                    break
            else:
                # Substring match: the cell value must contain one of the allowed values
                if not any(a in val for a in allowed):
                    passes = False
                    break
        if passes: kept.append(rec)
    return kept

def _records_to_list_meta(records: list[dict]) -> dict[str, list[str]]:
    if not records: return {col: [] for col in HADITH_LEVEL_LIST_COLUMNS}
    result: dict[str, list[str]] = {col: [] for col in HADITH_LEVEL_LIST_COLUMNS}
    for rec in records:
        for col in HADITH_LEVEL_LIST_COLUMNS:
            result[col].append(rec.get(col, ""))
    return result

# def retrieve_filtered(query: str, **filters) -> list[RetrievedResult]:
#     """
#     Retrieve up to cfg('retriever', 'k') results that match all supplied filters.
#     Filters are AND-combined across columns; within a column a list of values is OR-combined.
#     k_fetch is set to k_target * 10 so that post-filter we still get k_target hits
#     even when the filter is selective (e.g. a rare rawy value).
#     """
#     k_target = cfg("retriever", "k")
#     # Fetch 10× more than needed; rare filters may discard most candidates
#     k_fetch = k_target * 10
#     norm_filters = {
#         col: ([v.lower() for v in val] if isinstance(val, list) else [val.lower()])
#         for col, val in filters.items()
#     }
#     raw_docs = vectorstore.similarity_search(query, k=k_fetch)
#     results: list[RetrievedResult] = []
#     for doc in raw_docs:
#         records = _build_row_records(doc.metadata)
#         if not records: continue
#         kept_records = _filter_row_records(records, norm_filters)
#         if not kept_records: continue
#         filtered_list_meta = _records_to_list_meta(kept_records)
#         hadiths = filtered_list_meta.pop("hadith", [])
#         if not hadiths: continue
#         results.append(RetrievedResult(
#             sharh=doc.page_content,
#             hadiths=hadiths,
#             list_meta=filtered_list_meta,
#             scalar_meta={k: v for k, v in doc.metadata.items() if k in SHARH_LEVEL_SCALAR_COLUMNS}
#         ))
#         if len(results) >= k_target: break
#     return results
def retrieve_filtered(query: str, **filters) -> list[RetrievedResult]:
    k_target = cfg("retriever", "k")
    k_fetch  = k_target * 10

    norm_filters = {
        col: ([v.lower() for v in val] if isinstance(val, list) else [val.lower()])
        for col, val in filters.items()
    }

    raw_docs = vectorstore.similarity_search(query, k=k_fetch)

    results: list[RetrievedResult] = []
    seen_parents: set[int] = set()

    for doc in raw_docs:
        parent_id = doc.metadata.get("parent_id")
        if parent_id is None:
            continue

        # Stage 1: chunk-level filter using copied metadata
        chunk_passes = True
        for col, allowed in norm_filters.items():
            col_vals = doc.metadata.get(col, [])
            if isinstance(col_vals, str):
                try:
                    col_vals = ast.literal_eval(col_vals)
                except Exception:
                    col_vals = [col_vals]
            col_vals_lower = [str(v).lower() for v in col_vals]

            if col in EXACT_MATCH_COLUMNS:
                if not any(a in col_vals_lower for a in allowed):
                    chunk_passes = False
                    break
            else:
                if not any(any(a in v for a in allowed) for v in col_vals_lower):
                    chunk_passes = False
                    break

        if not chunk_passes:
            continue

        # Stage 2: deduplicate by parent_id
        if parent_id in seen_parents:
            continue
        seen_parents.add(parent_id)

        # Stage 3: fetch full parent from memory
        parent_doc = PARENT_STORE[parent_id]

        # Stage 4: filter parent's hadiths list
        records = _build_row_records(parent_doc.metadata)
        kept_records = _filter_row_records(records, norm_filters)
        if not kept_records:
            continue

        # # Stage 5: pick longest hadith (after filter)
        # kept_records = [max(
        #     kept_records,
        #     key=lambda r: len(normalize_arabic(r.get("hadith", "")).split())
        # )]

        filtered_list_meta = _records_to_list_meta(kept_records)
        hadiths = filtered_list_meta.pop("hadith", [])
        if not hadiths:
            continue

        results.append(RetrievedResult(
            sharh=parent_doc.page_content,
            hadiths=hadiths,
            list_meta=filtered_list_meta,
            scalar_meta={},
        ))

        if len(results) >= k_target:
            break

    return results
def print_results(results: list[RetrievedResult], max_hadith_preview: int = 120) -> None:
    for i, r in enumerate(results, 1):
        print(f"{' ─'*60}")
        def get_meta(key):
            val = r.list_meta.get(key, [])
            return [v if v.strip() else "Unknown" for v in val]

        print(f"[{i}] rawy={get_meta('rawy')}")
        print(f"    hokm={get_meta('hokm')}")
        print(f"    source={get_meta('source')}")
        print(f"    categories={r.list_meta.get('categories', 'N/A')}")
        print(f"    url={r.list_meta.get('url', 'N/A')}")
        print(f"    page={r.list_meta.get('page', 'N/A')}")
        print(f"    sharh[:150]: {r.sharh[:150].replace(chr(10),' ')}…")
        print(f"    hadiths ({len(r.hadiths)}):")
        for j, h in enumerate(r.hadiths):
            rawy_list = r.list_meta.get('rawy', [])
            label = rawy_list[j] if (j < len(rawy_list) and rawy_list[j].strip()) else 'Unknown'
            print(f"      [{j+1}] rawy={label!r} \n {h[:max_hadith_preview]}")
    print(f"{' ─'*60}")

In [27]:
def top_w_hadiths(results: list[RetrievedResult], w: int) -> list[RetrievedResult]:
    """
    For each RetrievedResult chunk, keep only the top-w hadiths with the most words.
    
    Args:
        results: List of RetrievedResult objects from retrieve_filtered().
        w: Maximum number of hadiths to keep per chunk (ranked by word count, descending).
    
    Returns:
        A new list of RetrievedResult objects, each with at most w hadiths.
        Chunks that end up with zero hadiths are dropped.
    
    Example:
        k=5 chunks × 20 hadiths each → 100 total
        top_w_hadiths(results, w=3) → at most 5×3 = 15 hadiths
    """
    if w <= 0:
        raise ValueError(f"w must be a positive integer, got {w}")

    trimmed_results: list[RetrievedResult] = []

    for r in results:
        if not r.hadiths:
            continue

        # Pair each hadith with its word count and original index
        indexed = [(i, h, len(normalize_arabic(h).split())) for i, h in enumerate(r.hadiths)]

        # Sort by word count descending, keep top-w
        top_indices = sorted(indexed, key=lambda x: x[2], reverse=True)[:w]

        # Re-sort by original index to preserve relative order
        top_indices.sort(key=lambda x: x[0])

        selected_indices = [idx for idx, _, _ in top_indices]

        # Rebuild hadiths list
        new_hadiths = [r.hadiths[i] for i in selected_indices]

        # Rebuild list_meta: slice each parallel list to the selected indices
        new_list_meta: dict[str, list] = {}
        for col, values in r.list_meta.items():
            new_list_meta[col] = [values[i] for i in selected_indices if i < len(values)]

        trimmed_results.append(RetrievedResult(
            sharh=r.sharh,
            hadiths=new_hadiths,
            list_meta=new_list_meta,
            scalar_meta=r.scalar_meta,
            score=r.score,
        ))

    return trimmed_results

In [28]:
def build_retriever():
    search_type = cfg("retriever", "search_type")
    k = cfg("retriever", "k")

    if search_type == "similarity":
        return vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": k})
    if search_type == "mmr":
        return vectorstore.as_retriever(
            search_type="mmr",
            search_kwargs={
                "k": k,
                "fetch_k": cfg("retriever", "fetch_k"),
                "lambda_mult": cfg("retriever", "lambda_mult"),
            },
        )
    raise ValueError(f"Unknown search_type: {search_type}")


retriever = build_retriever()
print(f"Retriever: {cfg('retriever', 'search_type')}, k={cfg('retriever', 'k')}")

Retriever: similarity, k=8

In [29]:
!pip install langchain-huggingface transformers torch accelerate
!pip install langchain-openai langchain-community langchain-groq

Requirement already satisfied: langchain-huggingface in /usr/local/lib/python3.12/dist-packages (1.2.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.10.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (1.4.8)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.24.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.30)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.12.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.14.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.34.2)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)
Requirement already satisfied: langchain-openai in /usr/local/lib/python3.12/dist-packages (1.3.3)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: langchain-groq in /usr/local/lib/python3.12/dist-packages (1.1.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (1.4.8)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.31.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.30)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.4.6)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.49)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from langchain-groq) (0.37.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.23.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.15.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain-openai) (0.14.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.10.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.4.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.7->langchain-openai) (3.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.41.4)

In [30]:
import os
import torch
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace, HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

def build_llm():
    """
    Build and return an LLM instance based on configuration.
    Supports: openai, ollama, groq, huggingface (endpoint & local)
    """
    provider = cfg("llm", "provider")
    temperature = cfg("llm", "temperature")
    print(provider)
    try:
        # --- OpenAI ---
        if provider == "openai":
            from langchain_openai import ChatOpenAI
            return ChatOpenAI(
                model=cfg("llm", "openai_model"), 
                temperature=temperature
            )
        
        # --- Ollama (local) ---
        if provider == "ollama":
            from langchain_community.chat_models import ChatOllama
            return ChatOllama(
                model=cfg("llm", "ollama_model"), 
                temperature=temperature
            )
        
        # --- Groq ---
        if provider == "groq":
            from langchain_groq import ChatGroq
            api_key = _get_api_key('GROQ_API_KEY')
            return ChatGroq(
                model=cfg("llm", "groq_model"), 
                temperature=temperature,
                groq_api_key=api_key,
            )
        
        # --- HuggingFace (via Inference API) ---
        if provider == "huggingface":
            api_key = _get_api_key('HF_TOKEN')
            repo_id = cfg("llm", "huggingface_model")
            
            llm_endpoint = HuggingFaceEndpoint(
                repo_id=repo_id,
                temperature=temperature,
                huggingfacehub_api_token=api_key,
                task="text-generation",
                max_new_tokens=CONFIG["llm"].get("max_new_tokens", 512),
            )
            return ChatHuggingFace(llm=llm_endpoint)
        
        # --- HuggingFace (Local pipeline) ---
        if provider == "huggingface_local":
            model_name = cfg("llm", "huggingface_model")
            print(f"Model name: {model_name}")
            tokenizer = AutoTokenizer.from_pretrained(model_name)
            model = AutoModelForCausalLM.from_pretrained(
                model_name,
                torch_dtype=torch.float16,
                device_map="auto",
                low_cpu_mem_usage=True,
            )
            
            pipe = pipeline(
                "text-generation",
                model=model,
                tokenizer=tokenizer,
                temperature=temperature,
            )
            
            llm_pipeline = HuggingFacePipeline(pipeline=pipe)
            return ChatHuggingFace(llm=llm_pipeline)
            
    except Exception as e:  
        raise e 

def _get_api_key(key_name):
    """Helper to get API key from Kaggle Secrets or environment variables"""
    # 1. Try Kaggle Secrets
    try:
        from kaggle_secrets import UserSecretsClient
        return UserSecretsClient().get_secret(key_name)
    except Exception:
        pass
        
    # 2. Fallback to OS Environment Variables
    return os.environ.get(key_name)

# --- Load LLM ---
try:
    llm = build_llm()
    if llm is not None:
        print(f"✅ LLM Loaded: {cfg('llm', 'provider')}")
    else:
        print("❌ Error: build_llm returned None unexpectedly.")
except Exception as e:
    print(f"❌ Error initializing LLM: {e}")
    llm = None

huggingface_local
Model name: silma-ai/SILMA-Kashif-2B-Instruct-v1.0

config.json:   0%|          | 0.00/974 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/34.4M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/288 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

Passing `generation_config` together with generation-related arguments=({'temperature'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

✅ LLM Loaded: huggingface_local

In [31]:
def format_docs(docs: list[Document]) -> str:
    """
    Format retrieved Documents for the LLM prompt, including hadiths in context.
    """
    blocks = []
    for i, doc in enumerate(docs, 1):
        meta = doc.metadata
        rawy   = meta.get("rawy", "")
        hokm   = meta.get("hokm", "")
        source = meta.get("source", "")
        page_id = meta.get("page_id", "")

        hadiths_raw = meta.get("hadith", [])
        if isinstance(hadiths_raw, str):
            try:
                hadiths_raw = ast.literal_eval(hadiths_raw)
            except Exception:
                hadiths_raw = [hadiths_raw]

        hadith_block = ""
        if hadiths_raw:
            hadith_lines = "\n".join(f"  - {h}" for h in hadiths_raw[:5])
            hadith_block = f"\nالأحاديث المرتبطة:\n{hadith_lines}"

        header = f"[{i}] page_id={page_id} | راوي={rawy} | حكم={hokm} | مصدر={source}"
        blocks.append(f"{header}\n{doc.page_content}{hadith_block}")

    return "\n\n---\n\n".join(blocks)


RAG_PROMPT = ChatPromptTemplate.from_messages([
    ("system", cfg("prompt", "system_role")),
    (
        "human",
        "السياق المسترجع:\n{context}\n\n"
        "السؤال: {question}\n\n"
        f"أجب باللغة: {cfg('prompt', 'language')}. اذكر page_id عند الاقتباس إن وُجد.",
    ),
])

prompt = RAG_PROMPT
prompt

ChatPromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], input_types={}, partial_variables={}, template='أنت عالم دين إسلامي متخصص، مهمتك الإجابة عن أسئلة المستخدمين بناءً فقط على النص المُسند إليك. امتنع تمامًا عن تأليف أي أقوال دينية أو اجتهادات شخصية غير واردة في النص المقدّم. عند الاستشهاد بالأحاديث، الزم بتخريجها مع ذكر المصدر (الكتاب، رقم الحديث)، ودرجة صحتها (صحيح، حسن، ضعيف، موضوع) بحسب ما ورد في المصادر المعتمدة. إذا لم تجد إجابة وافية في السياق المتاح، أو كان السؤال خارج نطاق النص، فلا تفتِ من عندك، بل وجّه المستخدم إلى ضرورة استشارة عالم أو مؤسسة دينية موثوقة للحصول على فتوى دقيقة ومناسبة. التزم بالأدب الجم، والوضوح، والاختصار، مع الحرص على تعزيز الطمأنينة النفسية للمستخدم.'), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template='السياق المسترجع:\n{context}\n\nالسؤال: {question}\n\nأجب باللغة: ar. اذكر page_id عند الاقتباس إن وُجد.'), additional_kwargs={})])

# RAG

In [32]:
from langchain_core.runnables import RunnableLambda, RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langchain_core.documents import Document

# Assuming your vector_store instance was already initialized as `vector_store`
# e.g., vector_store = Chroma(persist_directory=cfg("paths", "chroma_dir"), ...)

QUERY_FILTERS: dict = {}

def retrieve(question: str, k: int | None = None, **extra_filters) -> list[Document]:
    """
    Retrieve documents matching the user question from the vector store, 
    applying specified configuration settings and metadata filters.
    """
    # Fall back to your config if k is not explicitly provided
    search_k = k if k is not None else CONFIG["retriever"]["k"]
    search_type = CONFIG["retriever"]["search_type"]
    
    # Merge global filters with any query-time specific filters
    search_filters = {**QUERY_FILTERS, **extra_filters}
    
    # Configure the search arguments
    search_kwargs = {"k": search_k}
    if search_filters:
        search_kwargs["filter"] = search_filters
        
    if search_type == "mmr":
        search_kwargs["fetch_k"] = CONFIG["retriever"]["fetch_k"]
        search_kwargs["lambda_mult"] = CONFIG["retriever"]["lambda_mult"]

    # Initialize the base retriever dynamically based on configuration
    retriever = vectorstore.as_retriever(
        search_type=search_type,
        search_kwargs=search_kwargs
    )
    
    return retriever.invoke(question)


def format_docs(docs: list[Document]) -> str:
    """
    Formats the list of documents into a unified context string,
    including the page_id as requested by the system prompt.
    """
    formatted_chunks = []
    for doc in docs:
        page_id = doc.metadata.get("page_id", "غير محدد")
        chunk_text = f"--- [معرف الصفحة: {page_id}] ---\n{doc.page_content}"
        formatted_chunks.append(chunk_text)
        
    return "\n\n".join(formatted_chunks)


# --- Rebuilding your LCEL Chain safely ---

# Define templates exactly matching your LangChain structure
system_template = CONFIG["prompt"]["system_role"]
human_template = "السياق المسترجع:\n{context}\n\nالسؤال: {question}\n\nأجب باللغة: ar. اذكر page_id عند الاقتباس إن وُجد."

prompt_template = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template(system_template),
    HumanMessagePromptTemplate.from_template(human_template)
])

# Ensure your llm instance is initialized (from ChatHuggingFace wrapper)
# rag_llm = build_llm() 

# Complete LCEL Pipeline Chain
rag_chain = (
    {
        "context": RunnableLambda(lambda inputs: retrieve(inputs["question"])) | RunnableLambda(format_docs),
        "question": RunnablePassthrough()
    }
    | prompt_template
    | llm  # Your ChatHuggingFace pipeline wrapper instance
    | StrOutputParser()
)

In [33]:
from langchain_core.runnables import RunnableLambda, RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document

QUERY_FILTERS: dict = {}

def retrieve(question: str, k: int | None = None, **extra_filters) -> list[Document]:
    """
    Retrieve documents for a question.
    """
    active_filters = {**QUERY_FILTERS, **extra_filters}

    # Fetch configuration default value if k is not passed explicitly
    target_k = k if k is not None else CONFIG["retriever"]["k"]

    if active_filters:
        # Assumes retrieve_filtered is defined elsewhere in your codebase
        results = retrieve_filtered(question, **active_filters)
        docs = []
        for r in results:
            # Reconstruct metadata keys based on your specific backend objects
            meta = {**r.scalar_meta, **r.list_meta, "hadith": r.hadiths}
            docs.append(Document(page_content=r.sharh, metadata=meta))
        
        if target_k:
            docs = docs[:target_k]
        return docs
    else:
        # Assumes the base retriever instance is initialized globally
        docs = retriever.invoke(question)
        if target_k:
            docs = docs[:target_k]
        return docs

# --- Format Documents Helper ---
def format_docs(docs: list[Document]) -> str:
    """Formats retrieved document segments into a unified context block."""
    formatted_chunks = []
    for doc in docs:
        # Accessing page_id safely since your metadata dictionary structure packs scalar_meta
        page_id = doc.metadata.get("page_id", "غير محدد")
        chunk_text = f"--- [معرف الصفحة: {page_id}] ---\n{doc.page_content}"
        formatted_chunks.append(chunk_text)
    return "\n\n".join(formatted_chunks)

# --- Complete LCEL RAG Pipeline ---
rag_chain = (
    {
        # CRITICAL FIX: Extract just the 'question' string key from the dictionary 
        # instead of passing the whole dict into your retrieve function.
        "context": RunnableLambda(lambda inputs: retrieve(inputs["question"])) | format_docs,
        "question": RunnablePassthrough()
    }
    | prompt  # Your ChatPromptTemplate instance
    | llm     # Your ChatHuggingFace pipeline wrapper instance
    | StrOutputParser()
)

# Preview the chain structure
rag_chain;

In [34]:
import ast
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def ask(question: str, *, show_sources: bool = True, **filters) -> str:
    # 1. Merge global and local filters
    active_filters = {**QUERY_FILTERS, **filters}

    # 2. Print metadata/sources if requested
    if show_sources:
        print("--- Retrieved chunks ---")
        docs = retrieve(question, **filters)
        for doc in docs:
            meta = doc.metadata
            hadiths = meta.get("hadith", [])
            
            # Safely handle stringified lists from the vector database metadata
            if isinstance(hadiths, str):
                try:
                    hadiths = ast.literal_eval(hadiths)
                except Exception:
                    hadiths = [hadiths]  # Fallback if parsing fails
                    
            print(
                f"page_id={meta.get('page_id')} | "
                f"rawy={meta.get('rawy')} | "
                f"hokm={meta.get('hokm')} | "
                f"sharh[:100]={doc.page_content[:100]}..."
            )
            for h in hadiths[:2]:
                print(f"  hadith: {h[:120]}")
                
        if active_filters:
            print(f"Active filters: {active_filters}")
        print("--- Answer ---")

    # 3. Handle ad-hoc query filters by constructing a temporary dynamic chain
    if filters:
        temp_chain = (
            {
                # Fixed: Properly extract the "question" string from the incoming input dictionary
                "context": (lambda inputs: retrieve(inputs["question"], **filters)) | format_docs,
                "question": RunnablePassthrough()
            }
            | prompt
            | llm
            | StrOutputParser()
        )
        # Fixed: Pass a structured dictionary instead of a raw string
        return temp_chain.invoke({"question": question})

    # 4. Fallback to default pipeline if no query-time filters are applied
    # Fixed: Pass a structured dictionary here as well
    return rag_chain.invoke({"question": question})


# --- Run Test Query ---
QUESTION = "ما حكم سجود السهو إذا زاد الإمام في الصلاة؟"
answer = ask(QUESTION)
print(answer)

--- Retrieved chunks ---
page_id=None | rawy=['عبدالله بن مسعود', 'عبدالله بن مسعود', 'عبد الله', 'عبدالله بن مسعود', 'عبدالله بن مسعود', '', 'عبدالله بن مسعود'] | hokm=['إسناده صحيح على شرط مسلم', 'إسناده صحيح على شرط الشيخين', 'إسناده ثابت', '[صحيح]', 'صحيح', 'صحيح', '[صحيح]'] | sharh[:100]=إذا سها الإمام في الصلاة. ثم قال صلى الله عليه وسلم للناس : « وإذا شك أحدكم » فنسي في صلاته فلم يدر ...
page_id=None | rawy=['معاوية بن أبي سفيان', 'يوسف مولى عثمان', 'عبدالله بن جعفر', 'معاوية', 'معاوية بن أبي سفيان', 'معاوية بن أبي سفيان'] | hokm=['صحيح لغيره', 'صحيح لغيره', 'أخرجه في صحيحه', 'إسناده جيد', '[إسناده] حسن', '[إسناده] حسن'] | sharh[:100]=الصلاة عماد الدين ، وعلى المسلم أن يلتزم اتباع النبي صلى الله عليه وسلم في أدائها ، وقد علمها أصحابه...
page_id=None | rawy=['عبدالله بن مسعود'] | hokm=['[صحيح]'] | sharh[:100]=الصلاة عماد الدين ، وعلى العبد أن يلزم فيها الخشوع والتدبر ، وعدم الانشغال بأحوال الدنيا ، ولكنه قد ...
page_id=None | rawy=['المغيرة بن شعبة', 'المغيرة بن شعبة', 'المغيرة بن شعبة', 'المغيرة بن شعبة'] | hokm=['صحيح بطرقه', 'صحيح بطرقه', 'صحيح بطرقه', 'صحيح بطرقه'] | sharh[:100]=من الأحكام المتعلقة بصلاة الجماعة في حالة سهو الإمام أنه يشرع للمأمومين أن يقولوا سبحان الله ؛ حتى ي...
page_id=None | rawy=['ثوبان', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم', 'ثوبان مولى رسول الله صلى الله عليه وسلم'] | hokm=['حسن لغيره', 'حسن', 'حسن', 'حسن', 'حسن', 'حسن', 'ضعيف لكن له شواهد يتقوى بها', 'حسن'] | sharh[:100]=الصلاة أعظم أركان الإسلام العملية ، ولها أهميتها الخاصة في الشرع ، وعلى العبد أن يلزم فيها الخشوع وا...
page_id=None | rawy=['المغيرة بن شعبة'] | hokm=['إسناده صحيح'] | sharh[:100]=كان النبي صلى الله عليه وسلم يعلم أصحابه كل تفاصيل الصلاة ، وأحكامها ، وسننها ، وآدابها. وفي هذا الح...
page_id=None | rawy=['طلحة بن يزيد مولى الأنصار أبو حمزة', 'طلحة بن يزيد مولى الأنصار أبو حمزة', 'طلحة بن يزيد مولى الأنصار أبو حمزة'] | hokm=['سنده صحيح', 'إسناده صحيح', 'سنده صحيح'] | sharh[:100]=فرض الله تعالى الصلاة ، وبين النبي صلى الله عليه وسلم صفتها وقال : صلوا كما رأيتموني أصلي ؛ ولهذا فل...
page_id=None | rawy=['عبدالله بن مسعود', 'عبدالله بن مسعود', 'عبد الله', 'عبدالله بن مسعود', 'عبدالله بن مسعود', '', 'عبدالله بن مسعود'] | hokm=['إسناده صحيح على شرط مسلم', 'إسناده صحيح على شرط الشيخين', 'إسناده ثابت', '[صحيح]', 'صحيح', 'صحيح', '[صحيح]'] | sharh[:100]=الصلاة عماد الدين ، وعلى العبد أن يلزم فيها الخشوع والتدبر ، وترك الانشغال بأحوال الدنيا ، ولكنه قد ...
--- Answer ---

TemplateError: System role not supported

# Retrieve

In [35]:
# Test standalone retrieval with filtering
query = "ايه هو سجود السهو؟"

# Use retrieve_filtered directly to get RetrievedResult objects for print_results
results = retrieve_filtered(query)


print(f"Found {len(results)} results for: '{query}' with source filter\n")
print_results(results,max_hadith_preview=-1)

Found 8 results for: 'ايه هو سجود السهو؟' with source filter

 ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
[1] rawy=['Unknown', 'أبو سعيد الخدري', 'Unknown']
    hokm=['صحيح', 'ثابت', 'صحيح']
    source=['الفتاوى الكبرى', 'التمهيد', 'الفتاوى الكبرى']
    categories=['سهو - إذا لم يدر كم صلى ، سهو - السهو في الفرض والتطوع ، صلاة - الوسوسة في الصلاة ، إيمان - الجن والشياطين ، سهو - سجود السهو قبل التسليم', 'جن - صفة إبليس وجنوده ، سهو - إذا لم يدر كم صلى ، آداب عامة - الخطأ والنسيان ، إيمان - أعمال الجن والشياطين ، إيمان - الجن والشياطين', 'جن - صفة إبليس وجنوده ، سهو - إذا لم يدر كم صلى ، آداب عامة - الخطأ والنسيان ، إيمان - أعمال الجن والشياطين ، إيمان - الجن والشياطين']
    url=['https://dorar.net/hadith/sharh/215393', 'https://dorar.net/hadith/sharh/225405', 'https://dorar.net/hadith/sharh/225405']
    page=['1/360', '5/21', '1/360']
    sharh[:150]: فرض الله تعالى الصلاة، وبين النبي صلى الله عليه وسلم صفتها، وقال: صلوا كما رأيتموني أصلي؛ ولهذا فللصلاة أحكام تتعلق بشروطها وأركانها وسننها ومبطلاتها،…
    hadiths (3):
      [1] rawy='Unknown'
 - إذا شَكَّ أحَدُكم فلم يَدْرِ ثلاثًا صلَّى أم أربَعًا، فلْيَطَّرِحِ الشَّكَّ وليَبْنِ على ما تيقَّنَ، ثمَّ لِيَسجُدْ سَجْدَتينِ قَبْلَ أن يُسَلِّمَ، فإن صلَّى خَمْسًا شفَعَتا له صلاتَه، وإلَّا كانتا ترغيمًا للشَّيطان
      [2] rawy='أبو سعيد الخدري'
 - إذا لم يدْرِ أحدُكم ( كم ) صلَّى ثلاثًا أو أربعًا ، فليقُمْ فليُصلِّ ركعةً ، ثمَّ يسجُدُ بعد ذلك سجدتَيْن وهو جالسٌ ، فإن كان صلَّى خمسًا ، شفعتا له صلاتَه ، وإن كانت أربعًا ، أرغَمتِ الشَّيطان
      [3] rawy='Unknown'
 إذا شَكَّ أحَدُكم فلم يَدْرِ ثلاثًا صلَّى أم أربَعًا، فلْيَطَّرِحِ الشَّكَّ وليَبْنِ على ما تيقَّنَ، ثمَّ لِيَسجُدْ سَجْدَتينِ قَبْلَ أن يُسَلِّمَ، فإن صلَّى خَمْسًا شفَعَتا له صلاتَه، وإلَّا كانتا ترغيمًا للشَّيطان
 ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
[2] rawy=['عبدالله بن مسعود', 'عبدالله بن مسعود', 'أبو هريرة', 'عبدالله بن مسعود']
    hokm=['إسناده صحيح', 'صحيح', 'صحيح', 'صحيح']
    source=['تخريج المسند لشاكر', 'صحيح ابن ماجه', 'صحيح الترمذي', 'صحيح ابن ماجه']
    categories=['صلاة - صفة صلاة النبي صلى الله عليه وسلم ، سهو - سجود السهو بعد التسليم', 'اعتصام بالسنة - لزوم السنة ، صلاة - صفة صلاة النبي صلى الله عليه وسلم ، اعتصام بالسنة - الأمر بالتمسك بها ، سهو - سجود السهو بعد التسليم', 'صلاة - صفة صلاة النبي صلى الله عليه وسلم ، سهو - سجود السهو بعد التسليم', 'صلاة - صفة صلاة النبي صلى الله عليه وسلم ، سهو - سجود السهو بعد التسليم']
    url=['https://dorar.net/hadith/sharh/82263', 'https://dorar.net/hadith/sharh/42586', 'https://dorar.net/hadith/sharh/43311', 'https://dorar.net/hadith/sharh/82263']
    page=['5/196', '1012', '394', '1012']
    sharh[:150]: الصلاة عبادة روحية، وفيها يقف العبد بين يدي ربه سبحانه وتعالى، ويلزم فيه الخشوع والتدبر وعدم الانشغال بأحوال الدنيا، وربما يسهو فيها العبد، فينقص أو ي…
    hadiths (4):
      [1] rawy='عبدالله بن مسعود'
 - أنَّ النبيَّ صلَّى اللهُ عليهِ وسلَّمَ سجدهما بعد السلامِ وقال مرةً : إنَّ النبيَّ صلَّى اللهُ عليهِ وسلَّمَ سجد السجدتينِ في السهوِ بعدَ السلام
      [2] rawy='عبدالله بن مسعود'
 - أنَّ ابنَ مسعودٍ سجدَ سجدتيِ السَّهوِ بعدَ السَّلامِ وذَكرَ أنَّ النَّبيَّ صلَّى اللهُ عليهِ وسلَّمَ فعلَ ذلِ
      [3] rawy='أبو هريرة'
 - أنَّ النَّبيَّ صلَّى اللهُ عليْهِ وسلَّمَ سجدَهما بعدَ السَّلام
      [4] rawy='عبدالله بن مسعود'
 أنَّ ابنَ مسعودٍ سجدَ سجدتيِ السَّهوِ بعدَ السَّلامِ وذَكرَ أنَّ النَّبيَّ صلَّى اللهُ عليهِ وسلَّمَ فعلَ ذلِ
 ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
[3] rawy=['معاوية بن أبي سفيان', 'يوسف مولى عثمان', 'عبدالله بن جعفر', 'معاوية', 'معاوية بن أبي سفيان', 'معاوية بن أبي سفيان']
    hokm=['صحيح لغيره', 'صحيح لغيره', 'أخرجه في صحيحه', 'إسناده جيد', '[إسناده] حسن', '[إسناده] حسن']
    source=['تخريج المسند لشعيب', 'تخريج سنن الدارقطني', 'صحيح ابن خزيمة', 'الجوهر النقي', 'تخريج العواصم والقواصم', 'تخريج العواصم والقواصم']
    categories=['سهو - تنبيه الإمام إذا سها ، اعتصام بالسنة - أوامر النبي ونواهيه وتقريراته ، سهو - سجود السهو بعد التسليم', 'سهو - إذا قام من ركعتي الفريضة ، سهو - السهو في الفرض والتطوع ، سهو - تنبيه الإمام إذا سها ، سهو - سجود السهو قبل التسليم ، سهو - من سها عن التشهد الأوسط جبره بسجود السهو', 'سهو - السهو في الفرض والتطوع ، آداب عامة - الخطأ والنسيان', 'سهو - إذا قام من ركعتي الفريضة ، سهو - السهو في الفرض والتطوع ، سهو - تنبيه الإمام إذا سها ، سهو - سجود السهو بعد التسليم', 'سهو - إذا قام من ركعتي الفريضة ، سهو - السهو في الفرض والتطوع ، سهو - تنبيه الإمام إذا سها ، سهو - سجود السهو بعد التسليم', 'سهو - تنبيه الإمام إذا سها ، اعتصام بالسنة - أوامر النبي ونواهيه وتقريراته ، سهو - سجود السهو بعد التسليم']
    url=['https://dorar.net/hadith/sharh/172419', 'https://dorar.net/hadith/sharh/177345', 'https://dorar.net/hadith/sharh/179257', 'https://dorar.net/hadith/sharh/179468', 'https://dorar.net/hadith/sharh/149851', 'https://dorar.net/hadith/sharh/172419']
    page=['16917', '1407', '2/ 223', '2/334', '3/ 173', '3/ 173']
    sharh[:150]: الصلاة عماد الدين، وعلى المسلم أن يلتزم اتباع النبي صلى الله عليه وسلم في أدائها، وقد علمها أصحابه وعلمها أصحابه من بعدهم قولا وفعلا، وهذا الحديث يوضح…
    hadiths (6):
      [1] rawy='معاوية بن أبي سفيان'
 - أنَّه صلَّى أَمامَهم فقام في الصَّلاةِ وعليه جُلوسٌ، فسبَّحَ النَّاسُ، فتَمَّ على قيامِه، ثمَّ سجَدَ بنا سجدتَينِ وهو جالسٌ بعْدَ أنْ أَتَمَّ الصَّلاةَ، ثمَّ قعَدَ على المِنبرِ، فقال: سمِعتُ رسولَ اللهِ صلَّى اللهُ عليه وسلَّمَ يقولُ: مَن نَسيَ مِن صَلاتِهِ شَيئًا فلْيَسجُدْ مِثلَ هاتَينِ السَّجدتَينِ
      [2] rawy='يوسف مولى عثمان'
 - أنَّ مُعاويةَ صَلَّى بهم فقام في الرَّكعتَينِ وعليه الجُلوسُ؛ فسبَّحَ النَّاسُ به، فأبَى أنْ يَجلِسَ، حتى إذا جلَسَ للتَّسليمِ سجَدَ سَجدَتَينِ وهو جالسٌ، ثم قال: هكذا رَأيْتُ رسولَ اللهِ صلَّى اللهُ عليه وسلَّمَ يُصلِّي، وقال النَّيسابُوريُّ: ثُمَّ قال: رَأيْتُ رسولَ اللهِ صلَّى اللهُ عليه وسلَّمَ فعَلَ هذا
      [3] rawy='عبدالله بن جعفر'
 - مَن نسيَ شيئًا من صلاتِهِ فليسجُد سجدَتينِ وَهوَ جالس
      [4] rawy='معاوية'
 - أنَّ مُعاويةَ صلَّى أمامَهُم، فقامَ في الصَّلاةِ وعَليهِ جُلوسٌ، فسبَّحَ النَّاسُ، فَتمَّ على قيامِهِ، وسجدَ سَجدَتَينِ وَهوَ جالِسٌ بعدَ أن أتَمَّ الصَّلاةَ، ثمَّ قَعدَ علَى المنبَرِ، فَقالَ : إنِّي سَمِعْتُ رسولَ اللَّهِ صلَّى اللَّهُ عليهِ وسلَّمَ يقولُ : مَن نسيَ شيئًا في صلاتِهِ فليَسجُد مِثلَ هاتينِ السَّجدتين
      [5] rawy='معاوية بن أبي سفيان'
 - أنَّ مُعاويةَ صلَّى أمامَهم، فقامَ في الصَّلاةِ وعليه جُلوسٌ، فسبَّح الناسُ، فتَمَّ على قيامِه، ثم سَجَدَ سَجدتيْنِ وهو جالِسٌ بعدَ أنْ أتمَّ الصَّلاةَ، ثم قَعَدَ على المِنبَرِ، فقال: إني سَمِعتُ رسولَ اللهِ صلَّى اللهُ عليه وسلَّمَ يقولُ: مَن نَسِيَ شيئًا من صَلاتِهِ، فلْيسجُدْ مِثلَ هاتينِ السَّجدتينِ
      [6] rawy='معاوية بن أبي سفيان'
 أنَّ مُعاويةَ صلَّى أمامَهم، فقامَ في الصَّلاةِ وعليه جُلوسٌ، فسبَّح الناسُ، فتَمَّ على قيامِه، ثم سَجَدَ سَجدتيْنِ وهو جالِسٌ بعدَ أنْ أتمَّ الصَّلاةَ، ثم قَعَدَ على المِنبَرِ، فقال: إني سَمِعتُ رسولَ اللهِ صلَّى اللهُ عليه وسلَّمَ يقولُ: مَن نَسِيَ شيئًا من صَلاتِهِ، فلْيسجُدْ مِثلَ هاتينِ السَّجدتينِ
 ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
[4] rawy=['Unknown', 'أبو هريرة', '[أبو هريرة]', 'Unknown', 'عمران بن الحصين', 'معاوية بن حديج', 'أبو هريرة', 'نافع', 'عمران بن الحصين', 'عمران بن الحصين', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عمران بن الحصين', 'أبو هريرة', 'عمران بن حصين', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عمران بن الحصين', '[أبو هريرة]', 'معاوية بن خديج', 'معاوية بن خديج', 'أبو هريرة', 'أبو هريرة', '[أبو هريرة]', 'ذو اليدين السلمي', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن عمر', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن عمر', 'ذو اليدين السلمي', 'أبو بكر بن سليمان بن أبي حثمة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن عمر', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن عمر', 'عبدالله بن مالك بن بحينة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن عمر', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'ذو اليدين السلمي', 'ذو اليدين السلمي', 'أبو العريان السلمي', 'ابن مسعدة صاحب الجيش', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو بكر بن سليمان بن أبي حثمة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'ابن مسعدة', 'أبو هريرة', 'عبدالله بن عمر', 'أبو هريرة', 'أبو هريرة', 'عبدالله بن مسعود', 'أبو هريرة', 'أبو هريرة', 'ذو اليدين السلمي', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة']
    hokm=['مشهور صحيح', '[اشترط في المقدمة أنه] صحيح على طريقة بعض أهل الحديث', 'اتفق جميع أهل الإسلام على أنه حديث صحيح ثابت... ولا خلاف في ثبوته وصحته من طريق أبي هريرة، وهو في جميع دواوين الإسلام كذلك، وله طرق كثيرة، وألفاظ متعددة', 'إسناده صحيح', 'مقطوع وجاء متصلا في كتاب مسلم من وجه آخر', 'إسناده صحيح', 'إسناده صحيح', 'إسناده صحيح', 'أخرجه في صحيحه', 'أخرجه في صحيحه', 'إسناده صحيح على شرطهما', 'إسناده صحيح على شرط الشيخين', 'إسناده صحيح على شرط مسلم', 'إسناده صحيح على شرطهما', 'إسناده صحيح على شرطهما', 'إسناده صحيح على شرطهما', 'إسناده صحيح على شرطهما', 'إسناده قوي', 'إسناده صحيح على شرط الشيخين', 'إسناده صحيح على شرط الشيخين', 'إسناده صحيح على شرط الشيخين', 'إسناده صحيح على شرط الشيخين', 'إسناده صحيح على شرط مسلم', 'إسناده صحيح', 'أخرجه في صحيحه', 'إسناده صحيح', 'أخرجه في صحيحه', 'أخرجه في صحيحه', 'أخرجه في صحيحه', 'أخرجه في صحيحه', 'إسناده على شرط الصحيح، لكن ذكر أبو داود أن قوله: كبر، ثم كبر وسجد لم يذكرها غير حماد بن زيد، وكذا انفرد بقوله: فأومؤوا.', 'ثابت', 'إسناده صحيح', 'إسناده صحيح', 'ثابت', 'ثابت', 'ثابت', 'حسن غريب', 'إسنادها صحيح', 'احتج به ، وقال في المقدمة: (لم نحتج إلا بخبر صحيح من رواية الثقات مسند)', '[له] ثلاث عشر طريقاً كلها صحاح', 'إسناده على شرط الصحيح', 'احتج به ، وقال في المقدمة: (لم نحتج إلا بخبر صحيح من رواية الثقات مسند)', 'محفوظ', 'صحيح', 'غريب', 'مرسل يتصل من وجوه', 'مرسل يتصل من وجوه', 'إسناده صحيح', 'إسناده صحيح', 'أحسن سياقة لطرق حديث ذي اليدين', 'تفرد به أبو سلمة حماد بن أسامة وهو من الثقات', 'سكت عنه [وقد قال في رسالته لأهل مكة كل ما سكت عنه فهو صالح]', 'صحيح', 'صحيح', 'صحيح', 'صحيح', 'ثابت', 'ثابت', 'صحيح', '[صحيح]', '[صحيح]', '[صحيح]', '[صحيح]', '[صحيح]', '[صحيح]', '[صحيح]', '[صحيح]', 'صحيح', 'صحيح', 'صحيح', 'إسناده صحيح', 'صحيح', 'صحيح', 'صحيح', 'إسناده صحيح', 'صحيح', '[صحيح]', '[صحيح]', '[صحيح]', 'فيه معدي لين', '[فيه] مطير بن سليم معروف لم يذكره أحد بجرحة ومعدي بن سليمان يقال: إنه كان من الأبدال الفضلة', 'رجاله رجال الصحيح', 'رجاله رجال الصحيح خلا شيخ الطبراني إبراهيم بن محمد بن برة', 'إسناده صحيح متصل', 'إسناده صحيح', 'إسناده صحيح على شرط مسلم', 'إسناده صحيح متصل', 'إسناده صحيح على شرط مسلم', 'خبر ابن شهاب هذا في قصة ذي اليدين وهم غير محفوظ', 'سنده صحيح', 'سنده صحيح على شرط مسلم', 'أبو داود ولا رواه عن أبي داود إلا عبد الله بن عمران', 'لم يرو هذا الحديث عن معاوية إلا عمر بن يحيى ولا سمعناه إلا من هذا الشيخ', 'لم يرو هذا الحديث  عن ابن جريج إلا عبد الرزاق تفرد به إبراهيم بن محمد بن برة', 'لم يرو هذا الحديث عن طلحة بن نضر الحداني إلا علي بن نضر ويحيى بن أبي بكير الكرماني', 'لا نعلم رواه عن عبيد الله، عن نافع عن ابن عمر إلا أبو أسامة', 'حسن صحيح', 'إسناده صحيح', 'صحيح', 'إسناده صحيح', 'صحيح', 'صحيح', 'إسناده صحيح', 'رواته ثقات أئمة', 'صحيح', '[صحيح]']
    source=['أحكام القرآن لابن العربي', 'الإلمام بأحاديث الأحكام', 'الفتح الرباني', 'خلاصة الأحكام للنووي', 'غرر الفوائد المجموعة', 'كشف اللثام', 'نخب الافكار', 'نخب الافكار', 'صحيح ابن حبان', 'صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج صحيح ابن حبان', 'تخريج المسند لشعيب', 'تخريج المسند لشعيب', 'تخريج المسند لشعيب', 'تخريج المسند لشعيب', 'تخريج المسند لشعيب', 'تخريج سنن أبي داود', 'صحيح ابن خزيمة', 'الجوهر النقي', 'صحيح ابن خزيمة', 'صحيح ابن خزيمة', 'صحيح ابن خزيمة', 'صحيح ابن خزيمة', 'حاشية الإلمام لابن عبد الهادي', 'الأم', 'طرح التثريب', 'إرشاد الساري', 'الأوسط لابن المنذر', 'الأوسط لابن المنذر', 'الأوسط لابن المنذر', 'الإمتاع لابن حجر', 'طرح التثريب', 'المحلى', 'نخب الافكار', 'السنن والأحكام', 'المحلى', 'التمهيد', 'موافقة الخبر الخبر', 'موافقة الخبر الخبر', 'التمهيد', 'التمهيد', 'تخريج المسند لشاكر', 'تخريج المسند لشاكر', 'الاستذكار', 'السنن الكبرى للبيهقي', 'سنن أبي داود', 'صحيح أبي داود', 'صحيح أبي داود', 'صحيح أبي داود', 'صحيح ابن ماجه', 'اختلاف الحديث', 'اختلاف الحديث', 'صحيح أبي داود', 'صحيح البخاري', 'صحيح مسلم', 'صحيح مسلم', 'صحيح مسلم', 'صحيح البخاري', 'صحيح البخاري', 'صحيح البخاري', 'صحيح البخاري', 'صحيح ابن ماجه', 'صحيح النسائي', 'صحيح النسائي', 'صحيح النسائي', 'صحيح ابن ماجه', 'صحيح النسائي', 'صحيح النسائي', 'صحيح النسائي', 'صحيح الترمذي', 'صحيح البخاري', 'صحيح البخاري', 'صحيح البخاري', 'المهذب في اختصار السنن', 'الاستذكار', 'مجمع الزوائد', 'مجمع الزوائد', 'عمدة القاري', 'عمدة القاري', 'عمدة القاري', 'عمدة القاري', 'عمدة القاري', 'التمييز', 'نخب الافكار', 'نخب الافكار', 'المعجم الأوسط', 'المعجم الأوسط', 'المعجم الأوسط', 'المعجم الأوسط', 'البحر الزخار', 'صحيح النسائي', 'صحيح النسائي', 'صحيح النسائي', 'صحيح النسائي', 'صحيح النسائي', 'التمهيد', 'تخريج المسند لشاكر', 'السنن الكبرى للبيهقي', 'تخريج سنن الدارقطني', 'صحيح البخاري']

In [36]:
# Demonstration: per-hadith aligned filtering
# If a chunk has 10 hadiths and only 3 are from البخاري, only those 3 are returned.
query = "ايه هو سجود السهو؟"
results_filtered = retrieve_filtered(query, mohadth=["البخاري","مسلم"])
print(f"Filtered results: {len(results_filtered)}")
for r in results_filtered[:1]:
    print(f"  hadiths ({len(r.hadiths)}): rawy={r.list_meta.get('rawy')}")
    for j, h in enumerate(r.hadiths):
        print(f"    [{j}] rawy={r.list_meta['rawy'][j] if j < len(r.list_meta.get('rawy', [])) else '?'!r} | {h}")

Filtered results: 8
  hadiths (13): rawy=['أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو هريرة', 'أبو بكر بن سليمان بن أبي حثمة', 'أبو هريرة']
    [0] rawy='أبو هريرة' | - صَلَّى بنا رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم إحدى صَلاتَيِ العَشيِّ -قال ابنُ سيرينَ: سَمَّاها أبو هُرَيرةَ ولَكِن نَسيتُ أنا- قال: فصَلَّى بنا رَكعَتَينِ، ثُمَّ سَلَّمَ، فقامَ إلى خَشَبةٍ مَعروضةٍ في المَسجِدِ، فاتَّكَأ عليها كَأنَّه غَضبانُ، ووضَعَ يَدَه اليُمنى على اليُسرى، وشَبَّكَ بينَ أصابِعِه، ووضَعَ خَدَّه الأيمَنَ على ظَهرِ كَفِّه اليُسرى، وخَرَجَتِ السَّرَعانُ مِن أبوابِ المَسجِدِ، فقالوا: قَصُرَتِ الصَّلاةُ؟ وفي القَومِ أبو بَكرٍ وعُمَرُ، فهابا أن يُكَلِّماه، وفي القَومِ رَجُلٌ في يَدَيه طولٌ، يُقالُ له: ذو اليَدَينِ، قال: يا رَسولَ اللهِ، أنَسيتَ أم قَصُرَتِ الصَّلاةُ؟ قال: لَم أنسَ ولَم تُقصَرْ، فقال: أكما يقولُ ذو اليَدَينِ؟ فقالوا: نَعَم، فتَقدَّمَ فصَلَّى ما تَرَكَ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ وسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ، ثُمَّ كَبَّرَ وسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ، فرُبَّما سَألوه: ثُمَّ سَلَّمَ؟ فيَقولُ: نُبِّئتُ أنَّ عِمرانَ بنَ حُصَينٍ قال: ثُمَّ سَلَّمَ.
    [1] rawy='أبو هريرة' | - صَلَّى لَنا رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم صَلاةَ العَصرِ، فسَلَّمَ في رَكعَتَينِ، فقامَ ذو اليَدَينِ فقال: أقُصِرَتِ الصَّلاةُ يا رَسولَ اللهِ، أم نَسيتَ؟ فقال رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم: كُلُّ ذلك لَم يَكُنْ، فقال: قد كانَ بَعضُ ذلك يا رَسولَ اللهِ، فأقبَلَ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم على النَّاسِ، فقال: أصَدَقَ ذو اليَدَينِ؟ فقالوا: نَعَم، يا رَسولَ اللهِ، فأتَمَّ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم ما بَقيَ مِنَ الصَّلاةِ، ثُمَّ سَجَدَ سَجدَتَينِ وهو جالِسٌ، بَعدَ التَّسليمِ. [وفي روايةٍ]: صَلَّى رَكعَتَينِ مِن صَلاةِ الظُّهرِ، ثُمَّ سَلَّمَ فأتاه رَجُلٌ مِن بَني سُلَيمٍ، فقال: يا رَسولَ اللهِ، أقُصِرَتِ الصَّلاةُ أم نَسيتَ؟ وساقَ الحَديثَ.
    [2] rawy='أبو هريرة' | - بينا أنا أُصَلِّي مع النَّبيِّ صلَّى اللهُ عليه وسلَّم صَلاةَ الظُّهرِ سَلَّمَ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم مِنَ الرَّكعَتَينِ، فقامَ رَجُلٌ مِن بَني سُلَيمٍ، واقتَصَّ الحَديثَ.
    [3] rawy='أبو هريرة' | - صَلَّى بنا رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم إحدى صَلاتَيِ العَشيِّ؛ إمَّا الظُّهرَ، وإمَّا العَصرَ، فسَلَّمَ في رَكعَتَينِ، ثُمَّ أتى جِذعًا في قِبلةِ المَسجِدِ، فاستَنَدَ إليها مُغضَبًا، وفي القَومِ أبو بَكرٍ وعُمَرَ، فهابا أن يَتَكَلَّما، وخَرَجَ سَرَعانُ النَّاسِ، قُصِرَتِ الصَّلاةُ، فقامَ ذو اليَدَينِ، فقال: يا رَسولَ اللهِ، أقُصِرَتِ الصَّلاةُ أم نَسيتَ؟ فنَظَرَ النَّبيُّ صلَّى اللهُ عليه وسلَّم يَمينًا وشِمالًا، فقال: ما يقولُ ذو اليَدَينِ؟ قالوا: صَدَقَ، لَم تُصَلِّ إلَّا رَكعَتَينِ، فصَلَّى رَكعَتَينِ وسَلَّمَ، ثُمَّ كَبَّرَ، ثُمَّ سَجَدَ، ثُمَّ كَبَّرَ فرَفَعَ، ثُمَّ كَبَّرَ وسَجَدَ، ثُمَّ كَبَّرَ ورَفَعَ. قال: وأُخبِرتُ عن عِمرانَ بنِ حُصَينٍ أنَّه قال: وسَلَّمَ.
    [4] rawy='أبو هريرة' | - أنَّ رَسولَ اللهِ صلَّى اللهُ عليه وسلَّم انصَرَفَ مِنِ اثنَتَينِ، فقال له ذو اليَدَينِ: أقَصُرَتِ الصَّلاةُ أم نَسيتَ يا رَسولَ اللهِ؟ فقال رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم: أصَدَقَ ذو اليَدَينِ؟ فقال النَّاسُ: نَعَم، فقامَ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم، فصَلَّى اثنَتَينِ أُخرَيَينِ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ، فسَجَدَ مِثلَ سُجودِه أو أطولَ.
    [5] rawy='أبو هريرة' | - صَلَّى بنا النَّبيُّ صلَّى اللهُ عليه وسلَّم الظُّهرَ -أوِ العَصرَ- فسَلَّمَ، فقال له ذو اليَدَينِ: الصَّلاةُ يا رَسولَ اللهِ أنَقَصَت؟ فقال النَّبيُّ صلَّى اللهُ عليه وسلَّم لأصحابِه: أحَقٌّ ما يقولُ؟ قالوا: نَعَم، فصَلَّى رَكعَتَينِ أُخرَيَينِ، ثُمَّ سَجَدَ سَجدَتَينِ، قال سَعدٌ: ورَأيتُ عُروةَ بنَ الزُّبَيرِ صَلَّى مِنَ المَغرِبِ رَكعَتَينِ، فسَلَّمَ وتَكَلَّمَ، ثُمَّ صَلَّى ما بَقيَ وسَجَدَ سَجدَتَينِ، وقال: هَكَذا فعَلَ النَّبيُّ صلَّى اللهُ عليه وسلَّم.
    [6] rawy='أبو هريرة' | - أنَّ رَسولَ اللهِ صلَّى اللهُ عليه وسلَّم انصَرَفَ مِنِ اثنَتَينِ، فقال له ذو اليَدَينِ: أقَصُرَتِ الصَّلاةُ، أم نَسيتَ يا رَسولَ اللهِ؟ فقال رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم: أصَدَقَ ذو اليَدَينِ؟ فقال النَّاسُ: نَعَم، فقامَ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم فصَلَّى اثنَتَينِ أُخرَيَينِ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ، فسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ.
    [7] rawy='أبو هريرة' | - أنَّ رَسولَ اللهِ صلَّى اللهُ عليه وسلَّم انصَرَفَ مِنِ اثنَتَينِ، فقال له ذو اليَدَينِ: أقَصُرَتِ الصَّلاةُ يا رَسولَ اللهِ، أم نَسيتَ؟ فقال: أصَدَقَ ذو اليَدَينِ؟ فقال النَّاسُ: نَعَم، فقامَ رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم، فصَلَّى رَكعَتَينِ أُخرَيَينِ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ، ثُمَّ سَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ، ثُمَّ كَبَّرَ فسَجَدَ مِثلَ سُجودِه، ثُمَّ رَفَعَ.
    [8] rawy='أبو هريرة' | - صَلَّى النَّبيُّ صلَّى اللهُ عليه وسلَّم الظُّهرَ رَكعَتَينِ، فقيلَ: صَلَّيتَ رَكعَتَينِ، فصَلَّى رَكعَتَينِ، ثُمَّ سَلَّمَ، ثُمَّ سَجَدَ سَجدَتَينِ.
    [9] rawy='أبو هريرة' | - صَلَّى النَّبيُّ صلَّى اللهُ عليه وسلَّم إحدى صَلاتَيِ العَشيِّ -قال مُحَمَّدٌ: وأكثَرُ ظَنِّي العَصرَ- رَكعَتَينِ، ثُمَّ سَلَّمَ، ثُمَّ قامَ إلى خَشَبةٍ في مُقدَّمِ المَسجِدِ، فوضَعَ يَدَه عليها، وفيهم أبو بَكرٍ وعُمَرُ رَضيَ اللهُ عنهما، فهابا أن يُكَلِّماه، وخَرَجَ سَرَعانُ النَّاسِ فقالوا: أقَصُرَتِ الصَّلاةُ؟ ورَجُلٌ يَدعوه النَّبيُّ صلَّى اللهُ عليه وسلَّم ذو اليَدَينِ، فقال: أنَسيتَ أم قَصُرَت؟ فقال: لَم أنسَ ولَم تُقصَرْ، قال: بَلى قد نَسيتَ، فصَلَّى رَكعَتَينِ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ، فسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه، فكَبَّرَ، ثُمَّ وضَعَ رَأسَه، فكَبَّرَ، فسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ.
    [10] rawy='أبو هريرة' | - صَلَّى بنا النَّبيُّ صلَّى اللهُ عليه وسلَّم الظُّهرَ رَكعَتَينِ ثُمَّ سَلَّمَ، ثُمَّ قامَ إلى خَشَبةٍ في مُقدَّمِ المَسجِدِ، ووضَعَ يَدَه عليها، وفي القَومِ يَومَئذٍ أبو بَكرٍ وعُمَرُ، فهابا أن يُكَلِّماه، وخَرَجَ سَرَعانُ النَّاسِ، فقالوا: قَصُرَتِ الصَّلاةُ. وفي القَومِ رَجُلٌ، كان النَّبيُّ صلَّى اللهُ عليه وسلَّم يَدعوه ذا اليَدَينِ، فقال: يا نَبيَّ اللهِ، أنَسيتَ أم قَصُرَت؟ فقال: لم أنسَ ولم تَقصُرْ، قالوا: بَل نَسيتَ يا رَسولَ اللهِ، قال: صَدَقَ ذو اليَدَينِ، فقامَ فصَلَّى رَكعَتَينِ ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ فسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ، ثُمَّ وضَعَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ.
    [11] rawy='أبو بكر بن سليمان بن أبي حثمة' | - أن النبيَّ صلَّى اللهُ عليهِ وسلَّمَ صلَّى ركعتين ثم سلم فقال ذو الشمالين بنُ عبدِ عمرٍو: يا رسولَ اللهِ أقصُرتِ الصلاةُ أم نسيتَ؟ فقال رسولُ اللهِ صلَّى اللهُ عليهِ وسلَّمَ: لم تقصرِ الصلاةُ ولم أنسَ قال ذو الشِّمالين: قد كان ذلك يا رسولَ اللهِ فأقبل رسولُ اللهِ على الناسِ فقال: أصدق ذو اليدين؟ قالوا: نعم فقام رسولُ اللهِ صلَّى اللهُ عليهِ وسلَّمَ فأتمَّ ما بقيَ من الصلاةِ ولم يسجدِ السجدتين اللتين تسجدان إذا شكَّ الرجلُ في صلاتِه حين لقاه الناسُ.
    [12] rawy='أبو هريرة' | صَلَّى بنا رَسولُ اللهِ صلَّى اللهُ عليه وسلَّم إحدى صَلاتَيِ العَشيِّ -قال ابنُ سيرينَ: سَمَّاها أبو هُرَيرةَ ولَكِن نَسيتُ أنا- قال: فصَلَّى بنا رَكعَتَينِ، ثُمَّ سَلَّمَ، فقامَ إلى خَشَبةٍ مَعروضةٍ في المَسجِدِ، فاتَّكَأ عليها كَأنَّه غَضبانُ، ووضَعَ يَدَه اليُمنى على اليُسرى، وشَبَّكَ بينَ أصابِعِه، ووضَعَ خَدَّه الأيمَنَ على ظَهرِ كَفِّه اليُسرى، وخَرَجَتِ السَّرَعانُ مِن أبوابِ المَسجِدِ، فقالوا: قَصُرَتِ الصَّلاةُ؟ وفي القَومِ أبو بَكرٍ وعُمَرُ، فهابا أن يُكَلِّماه، وفي القَومِ رَجُلٌ في يَدَيه طولٌ، يُقالُ له: ذو اليَدَينِ، قال: يا رَسولَ اللهِ، أنَسيتَ أم قَصُرَتِ الصَّلاةُ؟ قال: لَم أنسَ ولَم تُقصَرْ، فقال: أكما يقولُ ذو اليَدَينِ؟ فقالوا: نَعَم، فتَقدَّمَ فصَلَّى ما تَرَكَ، ثُمَّ سَلَّمَ، ثُمَّ كَبَّرَ وسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ، ثُمَّ كَبَّرَ وسَجَدَ مِثلَ سُجودِه أو أطولَ، ثُمَّ رَفَعَ رَأسَه وكَبَّرَ، فرُبَّما سَألوه: ثُمَّ سَلَّمَ؟ فيَقولُ: نُبِّئتُ أنَّ عِمرانَ بنَ حُصَينٍ قال: ثُمَّ سَلَّمَ.

In [ ]:
# Example usage:
query = "ايه هو سجود السهو؟"
results_filtered = retrieve_filtered(query, mohadth=["البخاري","مسلم"])
trimmed = top_w_hadiths(results, w=3)  # at most 3 hadiths per chunk
for r in trimmed[:4]:
    # print(f"  hadiths ({len(r.hadiths)}): rawy={r.list_meta.get('rawy')}")
    # for j, h in enumerate(r.hadiths):
        # print(f"    [{j}] rawy={r.list_meta['rawy'][j] if j < len(r.list_meta.get('rawy', [])) else '?'!r} | {h}")
    # print("=" *150)
    print(r.hadiths)
    print("="*80)

# Evaluation

## Customization cheat sheet

| Goal | Change in `CONFIG` |
|------|-------------------|
| Use full dataset | `"max_rows": None` |
| Rebuild vector DB | `"reset_on_build": True` (run vector-store cell once) |
| More context per answer | Increase `retriever.k` or `chunk_size` |
| Diverse retrieval | `"search_type": "mmr"` |
| Local LLM | `"llm": {"provider": "ollama", ...}` + run Ollama |
| OpenAI embeddings | `"embeddings": {"provider": "openai", ...}` |
| Different fields in chunks | Edit `data.text_columns` / `metadata_columns` |
| Swap only the prompt | Edit `prompt.system_role` or the `RAG_PROMPT` cell |

In [37]:
import pandas as pd
eval_df = pd.read_csv("/kaggle/input/datasets/aliabdelmenam/gg-data/HAQA.csv")

In [38]:
eval_df.head(1)

,Record_Id,Question_Id,Question_Text,Quetion_Type,Question_Start_Word,Answer_ID,Full_Answer,Expert_Commentary,Hadith_Full_Answer,Hadith_Matn,Answer-Instances,Source_Name,Source_Link,Credibility,Question_ID_in_the_Orignal_Dataset
0,1,1,كيف نعبد الله؟,D,كيف,1.0,كَمَا أمرنا الله ورسوله مَعَ الإخلاص ( وَمَا أ...,كَمَا أمرنا الله ورسوله مَعَ الإخلاص,( مَن عمِلَ عمَلاً لَيْسَ عَلَيهِ أمْرُنا فَهُ...,مَن عمِلَ عمَلاً لَيْسَ عَلَيهِ أمْرُنا فَهُو...,مَن عمِلَ عمَلاً لَيْسَ عَلَيهِ أمْرُنا فَهُو...,كتاب عقيدة كل مسلم في سؤال و جواب لمحمد بن جمي...,https://www.noor-book.com/%D9%83%D8%AA%D8%A7%D...,yes,2

In [39]:
eval_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Record_Id                           1597 non-null   int64
 1   Question_Id                         1597 non-null   int64
 2   Question_Text                       1597 non-null   object
 3   Quetion_Type                        1597 non-null   object
 4   Question_Start_Word                 1597 non-null   object
 5   Answer_ID                           1597 non-null   float64
 6   Full_Answer                         1597 non-null   object
 7   Expert_Commentary                   1579 non-null   object
 8   Hadith_Full_Answer                  1597 non-null   object
 9   Hadith_Matn                         1597 non-null   object
 10  Answer-Instances                    1597 non-null   object
 11  Source_Name                         1597 non-null   object
 12  Source_Link                         1597 non-null   object
 13  Credibility                         1597 non-null   object
 14  Question_ID_in_the_Orignal_Dataset  1597 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 187.3+ KB

In [40]:
eval_df[eval_df['Question_Id'] == 445]

,Record_Id,Question_Id,Question_Text,Quetion_Type,Question_Start_Word,Answer_ID,Full_Answer,Expert_Commentary,Hadith_Full_Answer,Hadith_Matn,Answer-Instances,Source_Name,Source_Link,Credibility,Question_ID_in_the_Orignal_Dataset
512,513,445,الاستجمار بكم يكون من الحجارة ؟,D,بكم,1.0,إذا استجمر فليوتر، ولا يكون بأقل من ثلاث يعني:...,إذا استجمر فليوتر، ولا يكون بأقل من ثلاث يعني:...,حديث أَبِي هُرَيْرَةَ رضي الله عنه، أَنَّ رَسُ...,أَنَّ رَسُولَ الله ﷺ قَالَ: مَنِ اسْتَجْمَرَ ف...,فَليُوتِرْ,الاستدلال على كنز الأطفال للدكتور فيصل بن مسفر...,https://alilmia.com/sub_book91_5410.html,yes,٧٦٥
513,514,445,الاستجمار بكم يكون من الحجارة ؟,D,بكم,2.0,إذا استجمر فليوتر، ولا يكون بأقل من ثلاث يعني:...,إذا استجمر فليوتر، ولا يكون بأقل من ثلاث يعني:...,عَنْ سَلمَانَ رضي الله عنه، قَالَ: «نَهَانَا ...,قَالَ: «نَهَانَا رَسُولُ الله ﷺ أَنْ نَسْتَنْج...,نَهَانَا رَسُولُ الله ﷺ أَنْ نَسْتَنْجِيَ بِأَ...,الاستدلال على كنز الأطفال للدكتور فيصل بن مسفر...,https://alilmia.com/sub_book91_5410.html,yes,٧٦٥

## Evaluation config

In [41]:
from datetime import datetime, timezone
from pathlib import Path

EVAL_CONFIG = {
    "haqa_csv": "/kaggle/input/datasets/aliabdelmenam/gg-data/HAQA.csv",
    "max_samples": None,
    "random_seed": 42,
    "output_dir": PROJECT_ROOT / "eval_runs",
    "run_name": None,
    # Hadith-in-retrieval
    "retrieval": {
        "enabled": True,
        "min_substring_len": 12,
        "min_token_overlap": 0.45,
        "check_metadata_hadith_1": True,
    },
    # BLEU / ROUGE
    "bleu_rouge": {
        "enabled": True,
        # Strategy: compare ground-truth hadith against each retrieved hadith
        # individually and take the BEST score — correct when retrieval returns
        # many hadiths per chunk and the true answer is just one of them.
        "strategy": "best_match",   # "best_match" | "concatenate"
    },
    # RAGAS
    "ragas": {
        "enabled": True,
        "metrics": [
            "faithfulness",
            "answer_relevancy",
            "context_precision",
            "context_recall",
        ],
        "ground_truth_column": "Expert_Commentary",
        "max_contexts_for_ragas": None,
    },
}

def _eval_run_dir() -> Path:
    name = EVAL_CONFIG["run_name"] or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    run_dir = EVAL_CONFIG["output_dir"] / name
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir

EVAL_RUN_DIR = _eval_run_dir()
print(f"Eval outputs -> {EVAL_RUN_DIR}")

Eval outputs -> /kaggle/working/eval_runs/20260625_224905

In [42]:
# The error occurred because 'retrieve' was not defined in the current scope.
# Ensure cell 23371392 (which defines retrieve) has been executed.

try:
    koks = retrieve_filtered(query="ما حكم تربيةالدقن")
    print(f"Successfully retrieved {len(koks)} results.")
except NameError:
    print("Error: The 'retrieve' function is not defined. Please run the cell containing the RAG chain definition first.")

Successfully retrieved 8 results.

In [43]:
# FIX: RetrievedResult uses .hadiths and .list_meta instead of .metadata
if koks and len(koks) > 0:
    print(f"Printing hadiths for the first result (Total: {len(koks[0].hadiths)}):")
    for hadith in koks[0].hadiths[::-1]:
        print(f"- {hadith}")
else:
    print("No results found in 'koks'.")

Printing hadiths for the first result (Total: 4):
- أنَّ ابنَ عباسٍ سُئِلَ عمَّن ذَبَحَ دجاجةً فطيَّرَ رأسَها فقال ذكاةٌ وحيَّةٌ
- - أنَّ ابنَ عبَّاسٍ سُئلَ عمَّن ذبحَ دجاجةً فطَيَّرَ رأسَها فقالَ ذَكاةٌ وَحِيَّةٌ
- - عن ابنِ عبَّاسٍ سُئِلَ عن ذَبحِ دَجاجَةٍ طُيِّرَ رأسُها، فقال: ذَكاةٌ وَحِيَّةٌ.
- - أنَّ ابنَ عباسٍ سُئِلَ عمَّن ذَبَحَ دجاجةً فطيَّرَ رأسَها فقال ذكاةٌ وحيَّةٌ

In [44]:
all_hadiths = []
for doc in koks:
    # Use the .hadiths attribute instead of .metadata['hadith']
    hadiths = doc.hadiths
    print(f"Found {len(hadiths)} hadiths in this doc")
    all_hadiths.extend(hadiths)

print(f"\nTotal hadiths across {len(koks)} docs: {len(all_hadiths)}")

Found 4 hadiths in this doc
Found 3 hadiths in this doc
Found 9 hadiths in this doc
Found 3 hadiths in this doc
Found 12 hadiths in this doc
Found 7 hadiths in this doc
Found 3 hadiths in this doc
Found 3 hadiths in this doc

Total hadiths across 8 docs: 44

In [45]:
import re
from dataclasses import dataclass




def token_set(text: str) -> set[str]:
    return {t for t in normalize_arabic(text).split() if len(t) > 1}


def token_overlap_ratio(a: str, b: str) -> float:
    ta, tb = token_set(a), token_set(b)
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta)


def sequence_matcher(a: str, b: str) -> float:
    from difflib import SequenceMatcher
    return SequenceMatcher(None, normalize_arabic(a), normalize_arabic(b)).ratio()

In [46]:
# --- eval_retrieval_hadith.py ---
@dataclass
class HadithHitResult:
    hit: bool
    method: str | None          # substring | token_overlap | none
    best_overlap: float
    matched_doc_index: str | None


def hadith_in_retrieved_docs(
    hadith_matn: str,
    all_hadith: list[str], * , 
    min_substring_len: int | None = None, min_token_overlap: float | None = None) -> HadithHitResult:


    min_substring_len = min_substring_len or EVAL_CONFIG["retrieval"]["min_substring_len"]
    min_token_overlap = min_token_overlap or EVAL_CONFIG["retrieval"]["min_token_overlap"]

    target = normalize_arabic(hadith_matn)
    if len(target) < 3:
        return HadithHitResult(False, "none", 0.0, None)

    best_overlap = 0.0
    best_hadith = ""
    for i, hadith in enumerate(all_hadith):
        blob_norm = normalize_arabic(hadith)
        if len(target) >= min_substring_len and target in blob_norm:
            return HadithHitResult(True, "substring", 1.0, blob_norm)
        # overlap = token_overlap_ratio(hadith_matn, doc_retrieval_blob(doc))
        overlap = sequence_matcher(target, blob_norm)
        if overlap > best_overlap:
            best_overlap, best_hadith = overlap, blob_norm

    if best_overlap >= min_token_overlap:
        return HadithHitResult(True, "token_overlap", best_overlap, best_hadith)
    return HadithHitResult(False, "none", best_overlap, best_hadith)


def load_haqa_eval_frame() -> pd.DataFrame:
    path = EVAL_CONFIG["haqa_csv"]
    df = pd.read_csv(path)
    df = df.dropna(subset=["Question_Text", "Hadith_Matn"])
    max_n = EVAL_CONFIG["max_samples"]
    if max_n:
        df = df.sample(n=min(max_n, len(df)), random_state=EVAL_CONFIG["random_seed"])
    return df.reset_index(drop=True)

In [47]:
def run_haqa_retrieval_eval(haqa_df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, row in tqdm(haqa_df.iterrows(), total=len(haqa_df)):
        question = row["Question_Text"]
        hadith = row["Hadith_Matn"]

        # Retrieve filtered results
        # Using retrieve_filtered returns RetrievedResult objects
        docs = retrieve_filtered(query=normalize_arabic(question), mohadth=["البخاري","مسلم"])
        # docs = top_w_hadiths(docs, w=3)
        all_hadiths = []
        import ast
        for doc in docs:
            # Directly access the .hadiths attribute from the RetrievedResult object
            hadithss = doc.hadiths
            for ha in hadithss:
                all_hadiths.append(ha)
        hit = hadith_in_retrieved_docs(hadith, all_hadiths)
        rows.append({
            "Record_Id": row.get("Record_Id"),
            "Question_Id": row.get("Question_Id"),
            "Question_Text": question,
            "Hadith_Matn": hadith,
            "hadith_hit": hit.hit,
            "hit_method": hit.method,
            "best_token_overlap": round(hit.best_overlap, 4),
            # "matched_rank": (hit.matched_doc_index + 1) if hit.matched_doc_index is not None else None,
            # "retrieved_page_ids": [d.metadata.get("page_id") for d in docs],
            "n_retrieved": len(docs),
            "hadith":hit.matched_doc_index
        })
    return pd.DataFrame(rows)

if EVAL_CONFIG["retrieval"]["enabled"]:
    haqa_eval_df = load_haqa_eval_frame()
    retrieval_results_df = run_haqa_retrieval_eval(haqa_eval_df)

    hit_rate = retrieval_results_df["hadith_hit"].mean()
    print(f"Hadith-in-retrieval hit rate: {hit_rate:.1%} ({retrieval_results_df['hadith_hit'].sum()}/{len(retrieval_results_df)})")
    print(retrieval_results_df["hit_method"].value_counts(dropna=False))

    out_path = EVAL_RUN_DIR / "haqa_retrieval_hits.csv"
    retrieval_results_df.to_csv(out_path, index=False, encoding="utf-8-sig")

    import json
    summary_path = EVAL_RUN_DIR / "run_summary.json"
    summary_path.write_text(
        json.dumps(
            {
                "run_dir": str(EVAL_RUN_DIR),
                "n_samples": len(retrieval_results_df),
                "config_snapshot": CONFIG,
                "eval_config": {k: v for k, v in EVAL_CONFIG.items() if k != "haqa_csv"},
                "hadith_hit_rate": float(hit_rate),
                "hit_method_counts": retrieval_results_df["hit_method"].value_counts().to_dict(),
            },
            ensure_ascii=False,
            indent=2,
            default=str,
        ),
        encoding="utf-8",
    )
    print(f"Saved -> {out_path}, {summary_path}")
    retrieval_results_df.head()
else:
    print("Retrieval eval disabled in EVAL_CONFIG")

100%|██████████| 1597/1597 [01:59<00:00, 13.41it/s]

Hadith-in-retrieval hit rate: 42.1% (672/1597)
hit_method
none             925
token_overlap    662
substring         10
Name: count, dtype: int64
Saved -> /kaggle/working/eval_runs/20260625_224905/haqa_retrieval_hits.csv, /kaggle/working/eval_runs/20260625_224905/run_summary.json

In [48]:
if 'retrieval_results_df' in globals():
    null_hits = retrieval_results_df[retrieval_results_df['hadith_hit'].isna()]
    print(f"Number of null 'hadith_hit' values: {len(null_hits)}")
    if not null_hits.empty:
        display(null_hits)
    else:
        print("No Null values found in 'hadith_hit' column.")
else:
    print("Error: 'retrieval_results_df' not found. Please run the evaluation cell first.")

Number of null 'hadith_hit' values: 0
No Null values found in 'hadith_hit' column.

## BLEU & ROUGE Evaluation (Fix #2)

**The challenge:** the ground-truth has one hadith, but each retrieved chunk may
contain many hadiths (since we grouped by `sharh`).

**Strategy — `best_match`:**  
For each evaluation question, embed the ground-truth hadith and compare it
against every retrieved hadith individually. Report the **maximum** BLEU and
ROUGE score across all comparisons.  This is the correct choice because:
- Retrieval success means the right hadith is *somewhere* in the results.
- Averaging over all retrieved hadiths would dilute the score by unrelated hadiths.
- Taking the best match measures whether the pipeline found the correct hadith at all.

Macro-averages across questions are also reported.

In [49]:
!pip install nltk rouge-score --quiet

In [50]:
import nltk
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)

def rouge1_recall(reference: str, hypothesis: str) -> float:
    """How much of the reference is covered by the hypothesis."""
    ref_tokens = normalize_arabic(reference).split()
    hyp_tokens = set(normalize_arabic(hypothesis).split())
    if not ref_tokens:
        return 0.0
    matched = sum(1 for t in ref_tokens if t in hyp_tokens)
    return matched / len(ref_tokens)

def bleu1_precision(reference: str, hypothesis: str) -> float:
    """How much of the hypothesis actually appears in the reference."""
    ref_tokens = set(normalize_arabic(reference).split())
    hyp_tokens = normalize_arabic(hypothesis).split()
    if not hyp_tokens:
        return 0.0
    matched = sum(1 for t in hyp_tokens if t in ref_tokens)
    return matched / len(hyp_tokens)

def compute_best_match_scores(ground_truth_hadith: str, retrieved_hadiths: list[str]) -> dict[str, float]:
    if not retrieved_hadiths:
        return {"bleu": 0.0, "rouge1": 0.0}
    best = {"bleu": 0.0, "rouge1": 0.0}
    for hyp in retrieved_hadiths:
        # Using precision as a proxy for BLEU-1 and recall for ROUGE-1 per your request
        prec = bleu1_precision(ground_truth_hadith, hyp)
        rec = rouge1_recall(ground_truth_hadith, hyp)

        if prec > best["bleu"]:
            best["bleu"] = prec
        if rec > best["rouge1"]:
            best["rouge1"] = rec

    return best

print("Custom recall/precision metrics applied.")

Custom recall/precision metrics applied.

In [51]:
def run_bleu_rouge_eval(haqa_df: pd.DataFrame) -> pd.DataFrame:
    """
    Runs evaluation using custom precision (bleu) and recall (rouge1) metrics.
    """
    strategy = EVAL_CONFIG["bleu_rouge"]["strategy"]
    rows = []

    for _, row in tqdm(haqa_df.iterrows(), total=len(haqa_df), desc="Precision/Recall Eval"):
        question     = row["Question_Text"]
        ground_truth = row["Hadith_Matn"]

        # Retrieve filtered results with metadata constraint
        docs = retrieve_filtered(normalize_arabic(question), mohadth=["البخاري","مسلم"])
        # docs = top_w_hadiths(docs, w=3)
        retrieved_hadiths: list[str] = []
        for doc in docs:
            h = doc.hadiths
            retrieved_hadiths.extend(normalize_arabic(str(x)) for x in h)

        gt_norm = normalize_arabic(ground_truth)

        if strategy == "best_match":
            best_scores = compute_best_match_scores(gt_norm, retrieved_hadiths)
        else:
            # Defaulting to best_match for custom metrics as requested
            best_scores = compute_best_match_scores(gt_norm, retrieved_hadiths)

        rows.append({
            "Record_Id":           row.get("Record_Id"),
            "Question_Id":         row.get("Question_Id"),
            "Question_Text":       question,
            "Hadith_Matn":         ground_truth,
            "n_retrieved_hadiths": len(retrieved_hadiths),
            "precision_bleu":      round(best_scores["bleu"],   4),
            "recall_rouge1":       round(best_scores["rouge1"], 4),
        })

    return pd.DataFrame(rows)

def print_custom_summary(df: pd.DataFrame) -> None:
    print("=" * 55)
    print("Custom Metrics Summary (Best Match Strategy)")
    print(f"Precision (proxy for BLEU-1): {df['precision_bleu'].mean():.4f}")
    print(f"Recall (proxy for ROUGE-1):    {df['recall_rouge1'].mean():.4f}")
    print("=" * 55)

if EVAL_CONFIG["bleu_rouge"]["enabled"]:
    if "haqa_eval_df" not in globals():
        haqa_eval_df = load_haqa_eval_frame()

    bleu_rouge_df = run_bleu_rouge_eval(haqa_eval_df)
    print_custom_summary(bleu_rouge_df)

    bleu_rouge_path = EVAL_RUN_DIR / "haqa_custom_metrics.csv"
    bleu_rouge_df.to_csv(bleu_rouge_path, index=False, encoding="utf-8-sig")
    display(bleu_rouge_df.head())

Precision/Recall Eval: 100%|██████████| 1597/1597 [01:44<00:00, 15.27it/s]

=======================================================
Custom Metrics Summary (Best Match Strategy)
Precision (proxy for BLEU-1): 0.4366
Recall (proxy for ROUGE-1):    0.5106
=======================================================

,Record_Id,Question_Id,Question_Text,Hadith_Matn,n_retrieved_hadiths,precision_bleu,recall_rouge1
0,1,1,كيف نعبد الله؟,مَن عمِلَ عمَلاً لَيْسَ عَلَيهِ أمْرُنا فَهُو...,28,0.0690,0.6250
1,2,2,هل نعبد الله خوفا وطمعا؟,أسألُ اللهَ الجنّة وأعوذ بِهِ مِن النّار,35,0.3333,0.7143
2,3,3,ما هو الإحسان في العبادة؟,الإحسانُ أَنْ تعبُدَ اللهَ كأنّك تراه فإن لَم...,37,0.3333,0.9167
3,4,4,ما معنى لا إله إلا الله؟,من قَالَ لآ إله إِلاَّ الله وكَفَرَ بِمَا يُع...,44,0.4545,0.6000
4,5,5,ما هو التوحيد في صفات الله؟,ينزِلُ ربُّنا تبارك وتعالى فِي كلّ ليلةٍ إِلَى...,21,0.0430,0.2000

# W&B

In [ ]:
!pip install wandb
!pip install --upgrade wandb

In [ ]:
import os
import wandb
from kaggle_secrets import UserSecretsClient

# Fetch the key
user_secrets = UserSecretsClient()
wandb_key = user_secrets.get_secret("W&B_API")

# Set it globally in the environment
os.environ["WANDB_API_KEY"] = wandb_key
os.environ["WANDB_SILENT"] = "true"

In [ ]:
!wandb login

In [ ]:
import wandb

run = wandb.init(
    entity="RAG-Hadith",   # your team name
    project="temp project",       # shared project — same for everyone
    name="First Try (Normal chunking)",  # descriptive run name
    config={
        # Retrieval / Data parameters
        "embedding_model":  cfg("embeddings", "model_name"),
        "chunk_size":       "None",
        "chunk_overlap":    "None",
        "k":                cfg("retriever", "k"),
        
        "min_token_overlap": ".5",
        "description": "use normal chunking and hadith is from بخاري او مسلم only, but this time i have only chosed the top 3 longest hadith not all بخاري اي مسلم hadiths"
    }
)

In [ ]:
wandb.log({
    "Hit Rate": 33.2,
    "BELU": 0.4357,
    "ROUGE":0.4871
})

## RAGAS

In [ ]:
!pip install "ragas==0.2.15" "langchain-community==0.2.19" --quiet

In [ ]:
import json

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    answer_relevancy,
    context_precision,
    context_recall,
    faithfulness,
)

RAGAS_METRIC_MAP = {
    "faithfulness": faithfulness,
    "answer_relevancy": answer_relevancy,
    "context_precision": context_precision,
    "context_recall": context_recall,
}


def _ground_truth_from_row(row: pd.Series) -> str:
    col = EVAL_CONFIG["ragas"]["ground_truth_column"]
    if col in row.index and pd.notna(row[col]) and str(row[col]).strip():
        return str(row[col])
    if pd.notna(row.get("Full_Answer")):
        return str(row["Full_Answer"])
    return str(row.get("Expert_Commentary", ""))


def build_ragas_dataset(haqa_df: pd.DataFrame) -> Dataset:
    rows = []
    max_ctx = EVAL_CONFIG["ragas"]["max_contexts_for_ragas"]
    for _, row in haqa_df.iterrows():
        question = row["Question_Text"]
        docs = retrieve(question)
        contexts = [d.page_content for d in docs]
        if max_ctx:
            contexts = contexts[:max_ctx]
        answer = rag_chain.invoke(question)
        rows.append({
            "question": question,
            "answer": answer,
            "contexts": contexts,
            "ground_truth": _ground_truth_from_row(row),
            "hadith_matn": row["Hadith_Matn"],
        })
    return Dataset.from_list(rows)


def run_ragas_eval(haqa_df: pd.DataFrame):
    metric_names = EVAL_CONFIG["ragas"]["metrics"]
    metrics = [RAGAS_METRIC_MAP[m] for m in metric_names]

    dataset = build_ragas_dataset(haqa_df)
    result = evaluate(
        dataset=dataset,
        metrics=metrics,
        llm=llm,
        embeddings=embeddings,
    )
    return result


if EVAL_CONFIG["ragas"]["enabled"]:
    if "haqa_eval_df" not in globals():
        haqa_eval_df = load_haqa_eval_frame()

    ragas_result = run_ragas_eval(haqa_eval_df)
    ragas_per_question_df = ragas_result.to_pandas()

    per_row_path = EVAL_RUN_DIR / "ragas_per_question.csv"
    ragas_per_question_df.to_csv(per_row_path, index=False, encoding="utf-8-sig")

    metric_cols = [c for c in ragas_per_question_df.columns if c in EVAL_CONFIG["ragas"]["metrics"]]
    ragas_mean = ragas_per_question_df[metric_cols].mean(numeric_only=True).to_dict()

    # Combine all eval results into one summary
    summary: dict = {
        "run_dir": str(EVAL_RUN_DIR),
        "n_samples": len(haqa_eval_df),
        "config_snapshot": CONFIG,
        "eval_config": {k: v for k, v in EVAL_CONFIG.items() if k != "haqa_csv"},
        "ragas_mean": ragas_mean,
    }
    if "retrieval_results_df" in globals():
        summary["hadith_hit_rate"] = float(retrieval_results_df["hadith_hit"].mean())
    if "bleu_rouge_df" in globals():
        summary["bleu_rouge_mean"] = {
            col: round(float(bleu_rouge_df[col].mean()), 4)
            for col in bleu_rouge_df.columns
            if col.startswith(("best_", "concat_"))
        }

    summary_path = EVAL_RUN_DIR / "run_summary.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2, default=str), encoding="utf-8")

    print("RAGAS (mean over samples):")
    for k, v in ragas_mean.items():
        print(f"  {k}: {v:.4f}")
    print(f"Saved -> {per_row_path}, {summary_path}")
    ragas_per_question_df.head()
else:
    print("RAGAS eval disabled in EVAL_CONFIG")

In [ ]:
import json


def load_eval_summaries(runs_root: Path | None = None) -> pd.DataFrame:
    runs_root = runs_root or EVAL_CONFIG["output_dir"]
    rows = []
    for p in sorted(runs_root.glob("*/run_summary.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        row = {"run": p.parent.name}
        row.update(data.get("ragas_mean", {}))
        row["hadith_hit_rate"] = data.get("hadith_hit_rate")
        row.update(data.get("bleu_rouge_mean", {}))
        rows.append(row)
    return pd.DataFrame(rows)


# Example after 2+ trials:
# compare_df = load_eval_summaries()
# compare_df.sort_values("hadith_hit_rate", ascending=False)